### YamlMime:ModuleUnit
uid: learn.wwl.understand-advanced-data-visualization-concepts.design-configure-power-bi-reports-for-accessibility
title: Design and configure Power BI reports for accessibility
metadata:
  title: Design and configure Power BI reports for accessibility
  description: "Design and configure Power BI reports for accessibility"
  ms.date: 08/17/2022
  author: wwlpublish
  ms.author: anrudduc
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/4-design-configure-power-bi-reports-for-accessibility.md)]