### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-securing-server-client-endpoints.introduction-endpoint-security
title: Introduction to endpoint security
metadata:
  title: Introduction to endpoint security
  description: "SC-100 preparatory unit on the topic: introduction to endpoint security."
  ms.date: 3/14/2023
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/1-introduction-endpoint-security.md)]