### YamlMime:ModuleUnit
uid: learn.wwl.configure-azure-app-services.use-application-insights
title: Use Azure Application Insights
metadata:
  title: Use Azure Application Insights
  description: "Use Azure Application Insights"
  ms.date: 11/14/2023
  author: wwlpublish
  ms.author: cynthist
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/10-use-application-insights.md)]