### YamlMime:ModuleUnit
uid: learn.wwl.configure-azure-app-services.explore-continuous-integration-deployment
title: Explore continuous integration and deployment
metadata:
  title: Explore continuous integration and deployment
  description: "Explore continuous integration and deployment"
  ms.date: 11/14/2023
  author: wwlpublish
  ms.author: cynthist
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 2
content: |
  [!include[](includes/4-explore-continuous-integration-deployment.md)]