### YamlMime:ModuleUnit
uid: learn.wwl.configure-azure-app-services.add-deployment-slots
title: Add deployment slots
metadata:
  title: Add deployment slots
  description: "Add deployment slots"
  ms.date: 11/14/2023
  author: wwlpublish
  ms.author: cynthist
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/6-add-deployment-slots.md)]