### YamlMime:ModuleUnit
uid: learn.azdo.deploy-python.3-set-up-environment
title: Exercise - Set up your Azure DevOps environment
metadata:
  title: Exercise - Set up your Azure DevOps environment
  description: Create your Azure DevOps project and Azure resources.
  ms.date: 04/12/2023
  author: juliakm
  ms.author: jukullam
  ms.topic: unit
  ms.custom:
    - devx-track-python
durationInMinutes: 15
content: |
  [!include[](includes/3-set-up-environment.md)]
