### YamlMime:ModuleUnit
uid: learn.azdo.deploy-python.5-clean-up-environment
title: Exercise - Clean up your Azure DevOps environment
metadata:
  title: Exercise - Clean up your Azure DevOps environment
  description: Clean up your Azure DevOps project and your Azure resources.
  ms.date: 04/12/2023
  author: juliakm
  ms.author: jukullam
  ms.topic: unit
  ms.custom:
    - devx-track-python
durationInMinutes: 7
content: |
  [!include[](includes/5-clean-up-environment.md)]
