### YamlMime:ModuleUnit
uid: learn.wwl.install-configure-apps-session-host.demonstration-for-users
title: How to configure apps for users
metadata:
  title: How to configure apps for users
  description: "How to configure apps for users"
  ms.date: 08/04/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 13
content: |
  [!include[](includes/6-demonstration-configure-apps-for-users.md)]