### YamlMime:ModuleUnit
uid: learn.languages.python-install-vscode.exercise-write-first-application
title: Create your first Python application
metadata:
  title: Create your first Python application
  description: Create your first Python application
  ms.date: 01/09/2023
  author: softchris
  ms.author: chnoring
  ms.topic: unit
  ms.custom: team=nextgen, devdivchpfy22, devx-track-python, linux-related-content
  zone_pivot_groups: os
durationInMinutes: 5
content: |
  [!include[](includes/6-exercise-write-first-application.md)]
