### YamlMime:ModuleUnit
uid: learn.interact-with-data-blazor-web-apps.exercise-bind-controls-data-blazor-applications
title: Exercise - Bind controls to data in Blazor applications 
metadata:
  unitType: learning-content
  title: Exercise - Bind controls to data in Blazor applications
  description: "In this exercise, you'll finish adding an order sidebar and update the pizza configuration component."
  ms.date: 02/09/2023
  author: csharpfritz
  ms.author: jefritz
  ms.manager: markl
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/9-exercise-bind-controls-data-blazor-applications.md)]
