### YamlMime:ModuleUnit
uid: learn.cmu-cloud-computing.cloud-basics.cmu-build-apps-cloud.2-deployments
title: Deploy applications on the cloud
metadata:
  title: Deploy applications on the cloud
  description: Learn how to deploy apps on the cloud
  ms.date: 03/09/2022
  author: softchris
  ms.author: chnoring
  ms.topic: unit
  ms.custom: team=nextgen
durationInMinutes: 9
content: |
  [!include[](includes/2-deployments.md)]
