### YamlMime:ModuleUnit
uid: learn.customizing-dotnet-aspire-existing-resources.using-application-insights
title: Using Azure Application Insights to analyze telemetry
metadata:
  title: Using Azure Application Insights to analyze telemetry
  description: In this unit, you'll see how to customize an Azure deployment of a .NET Aspire app to export telemetry data into Azure Application Insights.
  author: camsoper
  ms.author: casoper
  ms.topic: unit
durationInMinutes: 7
content: |
  [!include[](includes/4-using-application-insights.md)]