### YamlMime:ModuleUnit
uid: learn.wwl.security-monitoring-automation-solutions.respond-threats-by-using-playbooks-with-automation-rules-microsoft-sentinel
title: Configure automation in Microsoft Sentinel
metadata:
  title: Configure automation in Microsoft Sentinel
  description: "Configure automation in Microsoft Sentinel"
  ms.date: 04/26/2024
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/6-respond-threats-by-using-playbooks-with-automation-rules-microsoft-sentinel.md)]