### YamlMime:ModuleUnit
uid: learn.wwl.manage-azure-stack-hci-virtual-machine-workloads.configure-affinity-of-vms
title: Configure affinity of Azure Stack HCI VMs
metadata:
  title: Configure affinity of Azure Stack HCI VMs
  description: "Configure affinity of Azure Stack HCI VMs"
  ms.date: 06/09/2021
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
durationInMinutes: 4
content: |
  [!include[](includes/3-configure-affinity-of-virtual-machines.md)]
quiz:
  title: "Knowledge check"
  questions:
  - content: "While evaluating the use of Windows Admin Center in Contoso's Azure Stack HCI environment, you decide to test affinity and anti-affinity rules. You deploy two VMs hosting resource-intensive SQL Server instances and want to ensure that they run on separate cluster nodes to prevent resource contention. What should you do? Your solution must minimize the number of rules you need to create."
    choices:
    - content: "Create one anti-affinity rule."
      isCorrect: true
      explanation: "Correct. A single anti-affinity rule referencing both VMs would suffice."
    - content: "Create one affinity rule."
      isCorrect: false
      explanation: "Incorrect. In this case, you need an anti-affinity rule because the VMs should run on separate cluster nodes."
    - content: "Create two anti-affinity rules."
      isCorrect: false
      explanation: "Incorrect. There is no need for the second rule. A single anti-affinity rule referencing both VMs would suffice."