### YamlMime:ModuleUnit
uid: learn.wwl.manage-azure-stack-hci-virtual-machine-workloads.configure-load-balancing-of-vms
title: Configure load balancing of Azure Stack HCI VMs
metadata:
  title: Configure load balancing of Azure Stack HCI VMs
  description: "Configure load balancing of Azure Stack HCI VMs"
  ms.date: 06/09/2021
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
durationInMinutes: 6
content: |
  [!include[](includes/4-configure-load-balancing-of-virtual-machines.md)]
quiz:
  title: "Knowledge check"
  questions:
  - content: "While evaluating the use of Windows Admin Center in Contoso's Azure Stack HCI environment, you decide to test the VM load-balancing behavior. You want the load-balancing mechanism to take effect whenever the utilization levels on individual cluster nodes exceed 70%. To achieve this, what should you configure in Windows Admin Center?"
    choices:
    - content: "Set the Aggressiveness property of the Virtual Machine load-balancing setting to Medium."
      isCorrect: true
      explanation: "Correct. The Medium value results in VM live migration from cluster nodes when the utilization level exceeds 70%."
    - content: "Set the Aggressiveness property of the Virtual Machine load-balancing setting to High."
      isCorrect: false
      explanation: "Incorrect. The High value triggers evaluation of the average utilization across all cluster nodes and results in VM live migration from nodes with the utilization level at least 5% above the average."
    - content: "Set the Aggressiveness property of the Virtual Machine load-balancing setting to Low."
      isCorrect: false
      explanation: "Incorrect. The Low value results in VM live migration from cluster nodes when the utilization level exceeds 80%."