### YamlMime:ModuleUnit
uid: learn.wwl.manage-azure-stack-hci-virtual-machine-workloads.configure-gpu-support-for-vms
title: Configure GPU support for Azure Stack HCI VMs
metadata:
  title: Configure GPU support for Azure Stack HCI VMs
  description: "Configure GPU support for Azure Stack HCI VMs"
  ms.date: 06/09/2021
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
durationInMinutes: 7
content: |
  [!include[](includes/5-configure-gpu-support-for-virtual-machines.md)]
quiz:
  title: "Knowledge check"
  questions:
  - content: "You want to evaluate the usage of Contoso's financial application by using a Linux VM running on Azure Stack HCI. Your Azure Stack HCI cluster hardware includes NVIDIA GPUs. What should you do before you assign the NVIDIA GPU to the Linux VM? Your solution must minimize the number of configuration changes."
    choices:
    - content: "Dismount the NVIDIA GPU on all cluster nodes."
      isCorrect: false
      explanation: "Incorrect. DDA associates the physical GPU on the cluster node that hosts the VM. Therefore, there is no need to dismount the GPU device on other cluster nodes."
    - content: "Configure the VM as a cluster role."
      isCorrect: false
      explanation: "Incorrect. DDA associates the physical GPU on the Hyper-V hosts to a VM, so it does not support failover in Azure Stack HCI scenarios. Effectively, you should provision the VM as stand-alone, rather than as a highly-available cluster role."
    - content: "Dismount the NVIDIA GPU on the cluster node that hosts the Linux VM."
      isCorrect: true
      explanation: "Correct. Because the GPU will be used exclusively by the VM, you have to disable and dismount it from the cluster node."