### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-external-identities.exercise-configure-external-collaboration
title: Exercise - configure external collaboration
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Exercise - configure external collaboration
  description: "Exercise - configure external collaboration"
  ms.date: 12/17/2024
  author: wwlpublish
  ms.author: roberts
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 5
content: |
  [!include[](includes/4-exercise-configure-external-collaboration.md)]