### YamlMime:ModuleUnit
uid: learn.wwl.hardening-windows-server.configure-privileged-access-workstations
title: Configure Privileged Access Workstations
metadata:
  title: Configure Privileged Access Workstations
  description: "Configure Privileged Access Workstations"
  ms.date: 06/01/2022
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/3-configure-privileged-access-workstations.md)]