### YamlMime:ModuleUnit
uid: learn.wwl.monitor-responses-events-azure-cosmos-db-sql-api.exercise-troubleshoot-application-using-sdk
title: 'Exercise: Troubleshoot an application using the Azure Cosmos DB for NoSQL SDK'
metadata:
  title: 'Exercise: Troubleshoot an application using the Azure Cosmos DB for NoSQL SDK'
  description: "Exercise: Troubleshoot an application using the Azure Cosmos DB for NoSQL SDK"
  ms.date: 10/18/2022
  author: wwlpublish
  ms.author: calopez
  ms.topic: unit
azureSandbox: false
labId: 107594
labModal: true
durationInMinutes: 20
content: |
  [!include[](includes/7-exercise-troubleshoot-application-using-sdk.md)]