### YamlMime:ModuleUnit
uid: learn.wwl.implement-high-availability-for-sap-workloads-azure.explore-activepassive-deployment-scenario
title: Explore the Active/Passive deployment scenario
metadata:
  title: Explore the Active/Passive deployment scenario
  description: "Explore the Active/Passive deployment scenario."
  ms.date: 08/13/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/18-explore-active-passive-deployment-scenario.md)]