### YamlMime:ModuleUnit
uid: learn.wwl.implement-high-availability-for-sap-workloads-azure.configure-combined-disaster-recovery
title: Configure combined high availability and disaster recovery
metadata:
  title: Configure combined high availability and disaster recovery
  description: "Configure combined high availability and disaster recovery"
  ms.date: 10/17/2023
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
durationInMinutes: 6
content: |
  [!include[](includes/19-configure-combined-high-availability-disaster-recovery.md)]