### YamlMime:ModuleUnit
uid: learn.wwl.implement-high-availability-for-sap-workloads-azure.configure-combined-disaster-recovery
title: Configure combined high availability and disaster recovery
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure combined high availability and disaster recovery
  description: "Explore important considerations to keep in mind when combining high availability and disaster recovery."
  ms.date: 09/20/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 6
content: |
  [!include[](includes/19-configure-combined-high-availability-disaster-recovery.md)]
