### YamlMime:ModuleUnit
uid: learn.wwl.implement-high-availability-for-sap-workloads-azure.explore-deployment-scenarios
title: Explore deployment scenarios
metadata:
  title: Explore deployment scenarios
  description: "Explore deployment scenarios"
  ms.date: 10/17/2023
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/5-explore-deployment-scenarios.md)]