### YamlMime:ModuleUnit
uid: learn.wwl.implement-high-availability-for-sap-workloads-azure.explore-deployment-scenarios
title: Explore deployment scenarios
metadata:
  title: Explore deployment scenarios
  description: "Explore three different deployment scenarios."
  ms.date: 07/30/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/5-explore-deployment-scenarios.md)]