### YamlMime:ModuleUnit
uid: learn.wwl.implement-high-availability-for-sap-workloads-azure.explore-of-sap-application-servers
title: Explore high availability of SAP application servers
metadata:
  title: Explore high availability of SAP application servers
  description: "Explore high availability of SAP application servers."
  ms.date: 08/13/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 2
content: |
  [!include[](includes/6-explore-high-availability-sap-application-servers.md)]