### YamlMime:ModuleUnit
uid: learn.innovate-applications-azure-cloud-technologies.4-infuse-application-artificial-intelligence
metadata:
  title: Infuse your applications with AI
  description: Using Azure services to enrich applications with Machine Learning and AI.
  ms.date: 04/14/2023
  author: Zimmergren
  ms.author: tozimmergren
  ms.topic: unit
title: Infuse your applications with AI
durationInMinutes: 9
content: |
  [!include[](includes/4-infuse-application-artificial-intelligence.md)]