### YamlMime:ModuleUnit
uid: learn.wwl.understand-app-service-deployment-slots.swap
title: Swap deployment slots
metadata:
  title: Swap deployment slots
  description: "Swap deployment slots"
  ms.date: 06/10/2024
  author: wwlpublish
  ms.author: jeffko
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 6
content: |
  [!include[](includes/4-swap-deployment-slots.md)]