### YamlMime:ModuleUnit
uid: learn.health-bot-built-in-scenarios.4-configure-built-in-scenario
title: Configure built-in scenarios
metadata:
  title: Configure built-in scenarios
  description: Learn how to configure the built-in scenarios and control every aspect of the Azure Health Bot instance functionality.
  author: Dwitrisha
  ms.author: chnoring
  ms.date: 03/09/2023
  ms.topic: unit
  ms.custom: team=nextgen
durationInMinutes: 10
content: |
  [!include[](includes/4-configure-built-in-scenario.md)]