### YamlMime:ModuleUnit
uid: learn.protect-endpoints-with-endpoint-manager.5-understand-endpoint-environment
title: Understand the endpoint environment
metadata:
  title: Understand the endpoint environment
  description: Learn about the cloud, on-premises, and co-management endpoint management with Microsoft Intune.
  ms.date: 05/05/2023
  author: Erikre
  ms.author: erikre
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/5-understand-endpoint-environment.md)]