### YamlMime:ModuleUnit
uid: learn.wwl.administer-manage-windows-server-iaas-vm-remotely.configure-just-time-administration
title: Configure just-in-time administration
metadata:
  title: Configure just-in-time administration
  description: "Configure just-in-time administration"
  ms.date: 07/03/2023
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 8
content: |
  [!include[](includes/5-configure-just-time-administration.md)]