### YamlMime:ModuleUnit
uid: learn.deploy-azure-vmware-solution.plan-azure-vmware-solution
metadata:
  title: Plan an Azure VMware Solution deployment
  description: Plan an Azure VMware Solution deployment.
  ms.date: 08/09/2023
  author: Orin-Thomas
  ms.author: orthomas
  ms.topic: unit
  ms.custom: team=cloud_advocates
  ms.contributors: shkuehn-03222021, orthomas-08092023
title: Plan an Azure VMware Solution deployment
durationInMinutes: 10
content: |
  [!include[](includes/2-plan-azure-vmware-solution-deployment.md)]
quiz:
  title: Check your knowledge
  questions:
  - content: "What version of vCenter is deployed with AVS?"
    choices:
    - content: "7.0 Update 3c"
      isCorrect: true
      explanation: "AVS deploys with vSphere 7.0 Update 3c."
    - content: "7.0 Update 1"
      isCorrect: false
      explanation: "AVS doesn't deploy with vSphere 7.0 Update 1."
    - content: "6.5 Update 2"
      isCorrect: false
      explanation: "AVS doesn't deploy with vSphere 6.5 Update 2."
  - content: "What is the minimum number of nodes required for Azure VMware Solution?"
    choices:
    - content: "4"
      isCorrect: false
      explanation: "For a minimum deployment, AVS requires fewer than four nodes."
    - content: "8"
      isCorrect: false
      explanation: "For a minimum deployment, AVS requires fewer than eight nodes."
    - content: "3"
      isCorrect: true
      explanation: "For a minimum deployment, AVS requires three nodes."
