### YamlMime:ModuleUnit
uid: learn.deploy-azure-vmware-solution.configure-nsx-t-network-components
metadata:
  title: Configure NSX-T network components
  description: Configure NSX-T network components.
  ms.date: 08/09/2023
  author: Orin-Thomas
  ms.author: orthomas
  ms.topic: unit
  ms.custom: team=cloud_advocates
  ms.contributors: shkuehn-03222021, orthomas-08092023
title: Configure NSX-T network components
durationInMinutes: 10
content: |
  [!include[](includes/6-configure-nsx-t-network-components.md)]
