### YamlMime:ModuleUnit
uid: learn.wwl.configure-azure-cosmos-db-sql-api.exercise-configure-throughput-for-azure-portal
title: 'Exercise: Configure throughput for Azure Cosmos DB for NoSQL with the Azure portal'
metadata:
  title: 'Exercise: Configure throughput for Azure Cosmos DB for NoSQL with the Azure portal'
  description: "Exercise: Configure throughput for Azure Cosmos DB for NoSQL with the Azure portal"
  ms.date: 10/22/2024
  author: wwlpublish
  ms.author: calopez
  ms.topic: unit
azureSandbox: false
labId: 107571
labModal: true
durationInMinutes: 15
content: |
  [!include[](includes/7-exercise-configure-throughput-for-azure-portal.md)]
