### YamlMime:ModuleUnit
uid: learn.wwl.explore-iot-hub-monitoring.exercise-configure-an-alert
title: Exercise - Configure an alert
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Exercise - Configure an alert
  description: "Configure an alert"
  ms.date: 11/05/2023
  author: kgremban
  ms.author: kgremban
  ms.custom: engagement-fy23
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 12
content: |
  [!include[](includes/5-exercise-configure-an-alert.md)]
