### YamlMime:ModuleUnit
uid: learn.wwl.implement-app-registration.implement-application-registration
title: Implement application registration
metadata:
  title: Implement application registration
  description: "Implement application registration"
  ms.date: 12/18/2024
  author: wwlpublish
  ms.author: roberts
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 1
content: |
  [!include[](includes/3-implement-application-registration.md)]