### YamlMime:ModuleUnit
uid: learn.wwl.implement-app-registration.configure-application-permission
title: Configure permission for an application
metadata:
  title: Configure permission for an application
  description: "Configure permission for an application"
  ms.date: 12/16/2024
  author: wwlpublish
  ms.author: roberts
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 1
content: |
  [!include[](includes/5-configure-application-permission.md)]