### YamlMime:ModuleUnit
uid: learn.wwl.implement-app-registration.grant-tenant-wide-admin-consent-to-application
title: Grant tenant-wide admin consent to applications
metadata:
  title: Grant tenant-wide admin consent to applications
  description: "Grant tenant-wide admin consent to applications"
  ms.date: 12/18/2024
  author: wwlpublish
  ms.author: roberts
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 5
content: |
  [!include[](includes/6-grant-tenant-wide-admin-consent-application.md)]