### YamlMime:ModuleUnit
uid: learn.wwl.implement-app-registration.manage-monitor-application-app-governance
title: Manage and monitor application by using app governance
metadata:
  title: Manage and monitor application by using app governance
  description: "Manage and monitor application by using app governance"
  ms.date: 12/17/2024
  author: wwlpublish
  ms.author: roberts
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 1
content: |
  [!include[](includes/9-manage-monitor-application-app-governance.md)]