### YamlMime:ModuleUnit
uid: learn.wwl.protect-data-transit-at-rest.configure-server-and-database-firewall
title: Configure server and database firewall rules
metadata:
  title: Configure server and database firewall rules
  description: "Configure server and database firewall rules"
  ms.date: 05/06/2022
  author: wwlpublish
  ms.author: jupadrao
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/3-configure-server-and-database-firewall.md)]