### YamlMime:ModuleUnit
uid: learn.authenticate-apps-with-managed-identities.5-exercise-configure-managed-identity-for-vm
metadata:
  title: Exercise - Configure a system-assigned managed identity for an Azure VM
  description: Configure a managed identity on a virtual machine. Create a system-assigned managed identity for the VM, and see how to access Azure resources from inside the VM.
  ms.date: 12/27/2023
  author: barclayn
  ms.author: barclayn
  ms.topic: unit
  ms.custom:
    - devx-track-azurecli
title: Exercise - Configure a system-assigned managed identity for an Azure VM
durationInMinutes: 6
interactive: bash
azureSandbox: true
content: |
  [!include[](includes/5-exercise-configure-managed-identity-for-vm.md)]
