### YamlMime:ModuleUnit
uid: learn.authenticate-apps-with-managed-identities.7-exercise-configure-app-using-managed-identity
metadata:
  title: Exercise - Configure a custom application in .NET by using managed identity
  description: Create a secret and store it in Azure Key Vault. Assign your VM's service principal permissions to get the secret. Build and run an app on your VM.
  ms.date: 12/27/2023
  author: barclayn
  ms.author: barclayn
  ms.topic: unit
  ms.custom:
    - devx-track-dotnet
title: Exercise - Configure a custom application in .NET by using managed identity
durationInMinutes: 10
interactive: bash
azureSandbox: true
content: |
  [!include[](includes/7-exercise-configure-app-using-managed-identity.md)]
