### YamlMime:ModuleUnit
uid: learn.azure.learn-introduction-tutorials-mrtk.1-3-exercise-configure-unity-for-windows-mixed-reality
title: Exercise - Configure Unity for Windows Mixed Reality
metadata:
  title: Exercise - Configure Unity for Windows Mixed Reality
  description: Introduction for Configuring Unity for Windows Mixed Reality
  ms.date: 09/30/2023
  author: marlenaklein-msft
  ms.author: marlenaklein
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/1-3-exercise-configure.md)]
