### YamlMime:ModuleUnit
uid: learn.azure.learn-introduction-tutorials-mrtk.1-4-configure-resources
title: Import and configure resources
metadata:
  title:  Import and configure resources
  description: Introduction for Importing and configuring resources
  ms.date: 09/30/2023
  author: marlenaklein-msft
  ms.author: marlenaklein
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/1-4-import-resources.md)]
