### YamlMime:ModuleUnit
uid: learn.azure.learn-introduction-tutorials-mrtk.1-5-exercise-configure-resources
title: Exercise - Import and configure resources
metadata:
  title: Exercise - Import and configure resources
  description: Exercise for Importing and configuring resources
  ms.date: 11/06/2024
  author: marlenaklein-msft
  ms.author: marlenaklein
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/1-5-exercise-import-resources.md)]
