### YamlMime:ModuleUnit
uid: learn.security-copilot-exercises.configure-plugin
title: Configure the Microsoft Sentinel plugin
metadata:
  title: Configure the Microsoft Sentinel plugin
  description: "Configure the Microsoft Sentinel plugin."
  ms.date: 06/06/2024
  author: wwlpublish
  ms.author: ceperezb
  ms.topic: unit
durationInMinutes: 15
content: |
  [!include[](includes/4-configure-plugin.md)]