### YamlMime:ModuleUnit
uid: learn.wwl.use-consistency-models-azure-cosmos-db-sql-api.exercise-configure-consistency-models-portal-sdk
title: 'Exercise: Configure consistency models in the portal and the Azure Cosmos DB for NoSQL SDK'
metadata:
  title: 'Exercise: Configure consistency models in the portal and the Azure Cosmos DB for NoSQL SDK'
  description: "Exercise: Configure consistency models in the portal and the Azure Cosmos DB for NoSQL SDK"
  ms.date: 10/17/2022
  author: wwlpublish
  ms.author: calopez
  ms.topic: unit
azureSandbox: false
labId: 107589
labModal: true
durationInMinutes: 15
content: |
  [!include[](includes/6-exercise-configure-consistency-models-portal-sdk.md)]