### YamlMime:ModuleUnit
uid: learn.iot.explore-azure-digital-twins-api-for-creating-a-graph.configure-postman-and-api-collections
title:  Configure Postman and API collections
interactive: bash
metadata:
  title:  Configure Postman and API collections
  description: Deploy an Azure Digital Twins instance, configure Postman for Azure Digital Twins, and learn about the Azure Digital Twin API categories.
  ms.date: 10/11/2023
  author: baanders
  ms.author: baanders
  ms.topic: unit
durationInMinutes: 20
content: |
  [!include[](includes/2-configure-postman-api-collections.md)]

quiz:
  title: Check your knowledge
  questions:
  
  - content: "True or false: You can use the same bearer token for Azure Digital Twins control plane and data plane API requests."
    choices:
    - content: "True"
      isCorrect: false
      explanation: "Incorrect. Control plane APIs and data plane APIs each require their own bearer token, granted from a different Azure resource endpoint."

    - content: "False"
      isCorrect: true
      explanation: "Correct.  Control plane APIs and data plane APIs each require their own bearer token, granted from a different Azure resource endpoint."

  - content: "Which of the following options is NOT an API category for Azure Digital Twins?"
    choices:
    - content: "Models"
      isCorrect: false
      explanation: "Incorrect. Models is one of the API categories. It contains operations like upload, validation, retrieval, and deletion of models."

    - content: "Digitaltwins"
      isCorrect: false
      explanation: "Incorrect. Digitaltwins is one of the API categories. It contains operations like creating, modifying, and deleting digital twins and their relationships."

    - content: "Graph"
      isCorrect: true
      explanation: "Correct. Graph is NOT one of the API categories. The digital twin graph, including twins and their relationships, is managed with the Digitaltwins APIs. "

    - content: "Query"
      isCorrect: false
      explanation: "Incorrect. Query is one of the API categories. You can use it to find sets of digital twins in the twin graph by their properties, models, or relationships. "

    - content: "Jobs"
      isCorrect: false
      explanation: "Incorrect. Jobs is one of the API categories. It's for managing long-running, asynchronous actions such as bulk import of models, twins, and relationships."