### YamlMime:ModuleUnit
uid: learn.manage-secrets-in-java-applications-zero-trust.5-exercise-secure-java-application-operator
title: Exercise - Secure a Java application from an IT operator perspective
metadata:
  title: Exercise - Secure a Java application from an IT operator perspective
  description: In this unit, you create an Azure Key Vault instance and use it to manage secrets.
  author: judubois
  ms.author: judubois
  ms.date: 05/28/2024
  ms.topic: unit
  ms.custom:
    - team=cloud_advocates
    - devx-track-azurecli
    - devx-track-extended-java
  ms.contributors:
  - judubois-12292021
durationInMinutes: 6
content: |
  [!include[](includes/5-exercise-secure-java-application-operator.md)]
