### YamlMime:ModuleUnit
uid: learn.azure.azure-netapp-files-sap-hana.understand-application-volume-groups
title: Understand Azure NetApp Files application volume groups
metadata:
  unitType: learning-content
  title: Understand application volume groups in Azure NetApp Files
  description: Learn the basic features and concepts of Azure NetApp Files.   
  ms.date: 02/27/2023
  author: b-ahibbard
  ms.author: anfdocs
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/3-understand-application-volume-groups.md)]