### YamlMime:ModuleUnit
uid: learn.wwl.configure-user-experience-settings.persistent-virtual-desktop-environments
title: Persistent virtual desktop environments
metadata:
  title: Persistent virtual desktop environments
  description: "Persistent virtual desktop environments"
  ms.date: 08/05/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/3-configure-persistent-non-persistent-desktop-environments.md)]