### YamlMime:ModuleUnit
uid: learn.wwl.configure-user-experience-settings.settings-through-group-policies
title: Configure user settings through group policies
metadata:
  title: Configure user settings through group policies
  description: "Configure user settings through group policies"
  ms.date: 08/05/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/4-configure-user-settings-through-group-policies.md)]