### YamlMime:ModuleUnit
uid: learn.wwl.configure-user-experience-settings.settings-through-endpoint-manager-policies
title: Configure user settings through Endpoint Manager policies
metadata:
  title: Configure user settings through Endpoint Manager policies
  description: "Configure user settings through Endpoint Manager policies"
  ms.date: 08/05/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/5-configure-user-settings-through-endpoint-manager-policies.md)]