### YamlMime:ModuleUnit
uid: learn.wwl.configure-user-experience-settings.configure-session-timeout-properties
title: Configure session timeout properties
metadata:
  title: Configure session timeout properties
  description: "Configure session timeout properties"
  ms.date: 08/05/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 8
content: |
  [!include[](includes/6-configure-session-timeout-properties.md)]