### YamlMime:ModuleUnit
uid: learn.wwl.configure-user-experience-settings.configure-universal-print
title: Configure Universal Print
metadata:
  title: Configure Universal Print
  description: "Configure Universal Print"
  ms.date: 08/05/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 10
content: |
  [!include[](includes/8-configure-universal-print.md)]