### YamlMime:ModuleUnit
uid: learn.wwl.integrate-microsoft-purview-azure-synapse-analytics.scan-workspaces
title: Connect Microsoft Purview to an Azure Synapse Analytics workspace
metadata:
  title: Connect Microsoft Purview to an Azure Synapse Analytics workspace
  description: "Connect Microsoft Purview to an Azure Synapse Analytics workspace"
  ms.date: 07/20/2023
  author: wwlpublish
  ms.author: rcaper
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/03-configure-purview-integration.md)]