### YamlMime:ModuleUnit
uid: learn.nvidia.use-automl-train-labeled-dataset-develop-production-model.configure-jupyter-notebook-execution-environment
title: Configure the Jupyter notebook execution environment
metadata:
  title: Configure the Jupyter notebook execution environment
  description: Configure the Jupyter notebook execution environment.
  author: toolboc
  ms.author: chnoring
  ms.date: 03/14/2022
  ms.custom: team=nextgen
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/3-configure-jupyter-notebook-execution-environment.md)]
