### YamlMime:ModuleUnit
uid: learn.wwl.offer-app-services-resource-provider-for-azure-stack-hub.plan-deployment
title: Plan an App Services resource provider deployment
metadata:
  title: Plan an App Services resource provider deployment
  description: "Plan an App Services resource provider deployment"
  ms.date: 03/29/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 10
content: |
  [!include[](includes/3-plan-app-services-resource-provider-deployment.md)]