### YamlMime:ModuleUnit
uid: learn.wwl.scale-manage-deployed-container-apps.examine-application-lifecycle-management-azure-container-apps
title: Examine application lifecycle management in Azure Container Apps
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Examine application lifecycle management in Azure Container Apps
  description: "Examine application lifecycle management in Azure Container Apps"
  ms.date: 10/31/2024
  author: wwlpublish
  ms.author: cahowd
  ms.topic: unit
  ms.custom:
  - ai-learning-hub
durationInMinutes: 5
content: |
  [!include[](includes/3-examine-application-lifecycle-management-azure-container-apps.md)]
