### YamlMime:ModuleUnit
uid: learn.wwl.protecting-monitoring-tuning-migrated-database.configure-read-replicas
title: Configure read replicas
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure read replicas
  description: "Configure read replicas"
  ms.date: 10/14/2024
  author: wwlpublish
  ms.author: jupadrao
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 11
content: |
  [!include[](includes/5-configure-read-replicas.md)]
