### YamlMime:ModuleUnit
uid: learn.wwl.implement-azure-container-apps.explore-distributed-application-runtime
title: Explore Dapr integration with Azure Container Apps
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Explore Dapr integration with Azure Container Apps
  description: "Explore Dapr integration with Azure Container Apps"
  ms.date: 07/16/2024
  author: wwlpublish
  ms.author: jeffko
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 5
content: |
  [!include[](includes/7-explore-distributed-application-runtime.md)]
