### YamlMime:ModuleUnit
uid: learn.wwl.implement-azure-container-apps.explore-distributed-application-runtime
title: Explore Dapr integration with Azure Container Apps
metadata:
  title: Explore Dapr integration with Azure Container Apps
  description: "Explore Dapr integration with Azure Container Apps"
  ms.date: 06/13/2023
  author: wwlpublish
  ms.author: jeffko
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/7-explore-distributed-application-runtime.md)]