### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.10-exercise-connect-with-your-azure-storage-configuration
title: Exercise - Upload an image to your Azure Storage account
metadata:
  title: Exercise - Upload an image to your Azure Storage account
  description: Exercise - Upload an image to your Azure Storage account
  ms.date: 10/01/2024
  author: pauljewellmsft
  ms.author: pauljewell
  ms.topic: unit
  ms.custom:
    - devx-track-extended-java
    - devx-track-js
  zone_pivot_groups: dev-lang-csharp-javascript
interactive: bash
azureSandbox: true
durationInMinutes: 5
content: |
  [!include[](includes/10-exercise-connect-with-your-azure-storage-configuration.md)]
