### YamlMime:ModuleUnit
uid: learn.azure.test-bicep-code-using-azure-pipelines.introduction
title: Introduction
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  unitType: introduction
  title: Introduction
  description: Introduction to testing Bicep code by using Azure Pipelines.
  ms.date: 10/31/2022
  author: mumian
  ms.author: jgao
  ms.topic: unit
  ms.custom:
    - devx-track-bicep
durationInMinutes: 2
content: |
  [!include[](includes/1-introduction.md)]

