### YamlMime:ModuleUnit
uid: learn.building-end-to-end-data-governance-master-data-stack-with-microsoft-purview-cluedin.exercise-deploy-configure-environment
title: Deploy and configure your environment
metadata:
  title: Deploy and configure your environment
  description: "Configure your environment for master data management and data governance with Microsoft Purview and CluedIn. Deploy Azure Data Lake Storage (ADLS) Gen2 and Azure Data Factory resources to create a full data stack."
  ms.date: 05/28/2024
  author: whhender
  ms.author: whhender
  ms.topic: unit
durationInMinutes: 30
content: |
  [!include[](includes/2-exercise-deploy-configure-environment.md)]