### YamlMime:ModuleUnit
uid: learn.wwl.plan-implement-business-continuity-disaster-recovery.fslogix-configuration
title: FSLogix configuration
metadata:
  title: FSLogix configuration
  description: "FSLogix configuration"
  ms.date: 03/15/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/4-fslogix-configuration.md)]