### YamlMime:ModuleUnit
uid: learn.wwl.implement-hybrid-network-infrastructure.configure-azure-virtual-wan
title: Configure Azure Virtual WAN
metadata:
  title: Configure Azure Virtual WAN
  description: "Configure Azure Virtual WAN"
  ms.date: 03/26/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - e2e-hybrid
durationInMinutes: 10
content: |
  [!include[](includes/6-configure-azure-virtual-wide-area-network.md)]