### YamlMime:ModuleUnit
uid: learn.wwl.implement-hybrid-network-infrastructure.implement-dns-hybrid-environments
title: Implement DNS in hybrid environments
metadata:
  title: Implement DNS in hybrid environments
  description: "Implement DNS in hybrid environments"
  ms.date: 03/26/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - e2e-hybrid
durationInMinutes: 9
content: |
  [!include[](includes/7-implement-domain-name-system-hybrid-environments.md)]