### YamlMime:ModuleUnit
uid: learn.oxford.develop-secure-iot-solutions-for-azure-sphere-iot-hub.how-partnering-with-rtos-environment
title: How to send Azure RTOS real-time room environment sensor data to IoT Hub
metadata:
  title: How to send Azure RTOS real-time room environment sensor data to IoT Hub
  description: In this section, send Azure RTOS real-time room environment sensor data to IoT Hub
  ms.date: 12/11/2020
  author: leestott
  ms.author: leestott
  ms.topic: unit
  ms.custom: team=nextgen
  ms.service: iot-hub
durationInMinutes: 4 # dummy number at present
content: |
  [!include[](includes/15-how-partnering-with-rtos-environment.md)]
