### YamlMime:ModuleUnit
uid: learn.oxford.develop-secure-iot-solutions-for-azure-sphere-iot-hub.exercise-partnering-with-rtos-environment
title: Exercise - Send Azure RTOS real-time room environment sensor data to IoT Hub
metadata:
  title: Exercise - Send Azure RTOS real-time room environment sensor data to IoT Hub
  description: In this section, we send Azure RTOS real-time room environment sensor data to IoT Hub
  ms.date: 12/11/2020
  author: leestott
  ms.author: leestott
  ms.topic: unit
  ms.custom: team=nextgen
  ms.service: iot-hub
durationInMinutes: 10 # dummy number at present
content: |
  [!include[](includes/16-exercise-partnering-with-rtos-environment.md)]
