### YamlMime:ModuleUnit
uid: learn.oxford.develop-secure-iot-solutions-for-azure-sphere-iot-hub.how-azure-sphere-security
title: How to secure an Azure Sphere
metadata:
  title: How to secure an Azure Sphere
  description: In this section, learn how to secure an Azure Sphere
  ms.date: 12/11/2020
  author: leestott
  ms.author: leestott
  ms.topic: unit
  ms.custom: team=nextgen
  ms.service: iot-hub
durationInMinutes: 4 # dummy number at present
content: |
  [!include[](includes/8a-how-azure-sphere-security.md)]
