### YamlMime:ModuleUnit
uid: learn.oxford.develop-secure-iot-solutions-for-azure-sphere-iot-hub.exercise-azure-sphere-security
title: Exercise - Secure an Azure Sphere application
metadata:
  title: Exercise - Secure an Azure Sphere application
  description: In this section, we secure an Azure Sphere application.
  ms.date: 12/11/2020
  author: leestott
  ms.author: leestott
  ms.topic: unit
  ms.custom: team=nextgen
  ms.service: iot-hub
durationInMinutes: 5 # dummy number at present
content: |
  [!include[](includes/8b-exercise-azure-sphere-security.md)]
