### YamlMime:ModuleUnit
uid: learn.intro-configuration-management-hdinsight-aks.5-exercise-customize-cluster-configuration
title: Exercise – Customize cluster configuration
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  unitType: learning-content  
  title: Exercise – Customize cluster configuration
  description: Exercise – Customize cluster configuration
  ms.date: 01/24/2024  
  author: sairamyeturi
  ms.author: sairamyeturi
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/5-exercise-customize-cluster-configuration.md)]

