### YamlMime:ModuleUnit
uid: learn.wwl.implement-windows-server-iaas-vm-ip-addressing-routing.configure-private-ip-address-for-virtual-machine-using-azure-portal
title: Configure a private IP address for a virtual machine using the Azure portal
metadata:
  title: Configure a private IP address for a virtual machine using the Azure portal
  description: "Configure a private IP address for a virtual machine using the Azure portal"
  ms.date: 08/16/2020
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
durationInMinutes: 4
content: |
  [!include[](includes/05-configure-private-ip-address-using-azure-portal.md)]