### YamlMime:ModuleUnit
uid: learn.student-evangelism.optimize-basketball-player-rest-breaks.2-set-up-local-environment
metadata:
  title: Exercise - Set up your local environment for data science coding
  description: Set up your local environment for data science coding
  ms.date: 10/12/2022
  author: softchris
  ms.author: chnoring
  ms.topic: unit
  ms.custom:
    - team=nextgen
    - devx-track-python
title: Exercise - Set up your local environment for data science coding
durationInMinutes: 5
content: |
  [!include[](includes/2-set-up-local-environment.md)]
