### YamlMime:ModuleUnit
uid: learn.wwl.manage-azure-stack-hub-registration.register-connected-environment
title: Register in a connected environment
metadata:
  title: Register in a connected environment
  description: "Register in a connected environment"
  ms.date: 03/29/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 8
content: |
  [!include[](includes/2-register-connected-environment.md)]