### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-security-posture-management-hybrid-multicloud-environments.integrate-hybrid-multi-cloud-environments-azure-arc
title: Integrate hybrid and multicloud environments with Azure Arc
metadata:
  title: Integrate hybrid and multicloud environments with Azure Arc
  description: "SC-100 preparatory unit on the topic: Integrate hybrid and multicloud environments with Azure Arc."
  ms.date: 3/19/2023
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/7-integrate-hybrid-multi-cloud-environments-azure-arc.md)]
