### YamlMime:ModuleUnit
uid: learn.wwl.deploy-deep-learning-workloads-to-production-azure-machine-learning.standardize-model-formats-scale-model-deployment-onnx-triton
title: Standardize model formats and scale model deployment with ONNX and Triton
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Standardize model formats and scale model deployment with ONNX and Triton
  description: Standardize model formats and scale model deployment with ONNX and Triton
  author: wwlpublish
  ms.author: madiepev
  ms.date: 07/10/2024
  ms.topic: unit
  ms.collection:
    - wwl-ai-copilot
  ms.custom:
    - build-2023
    - build-2023-dataai
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/3-standardize-model-formats-scale-model-deployment-onnx-triton.md)]

