### YamlMime:ModuleUnit
uid: learn.wwl.deploy-microsoft-defender-for-endpoints-environment.create-your-environment
title: Create your environment
metadata:
  title: Create your environment
  description: "Create your environment"
  ms.date: 12/19/2024
  author: wwlpublish
  ms.author: kelawson
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 4
content: |
  [!include[](includes/2-create-your-environment.md)]