### YamlMime:ModuleUnit
uid: learn.wwl.deploy-microsoft-defender-for-endpoints-environment.create-your-environment
title: Create your environment
metadata:
  title: Create your environment
  description: "Create your environment"
  ms.date: 02/17/2023
  author: wwlpublish
  ms.author: kelawson
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/2-create-your-environment.md)]