### YamlMime:ModuleUnit
uid: learn.wwl.deploy-microsoft-defender-for-endpoints-environment.configure-device-groups
title: Configure device groups
metadata:
  title: Configure device groups
  description: "Configure device groups"
  ms.date: 12/19/2024
  author: wwlpublish
  ms.author: kelawson
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 5
content: |
  [!include[](includes/7-configure-device-groups.md)]