### YamlMime:ModuleUnit
uid: learn.wwl.deploy-microsoft-defender-for-endpoints-environment.configure-environment-advanced-features
title: Configure environment advanced features
metadata:
  title: Configure environment advanced features
  description: "Configure environment advanced features"
  ms.date: 02/17/2023
  author: wwlpublish
  ms.author: kelawson
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/8-configure-environment-advanced-features.md)]