### YamlMime:ModuleUnit
uid: learn.wwl.implement-access-management-for-azure-resources.create-configure-managed-identities
title: Create and configure managed identities
metadata:
  title: Create and configure managed identities
  description: "Create and configure managed identities"
  ms.date: 10/30/2023
  author: wwlpublish
  ms.author: roberts
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/4-create-configure-managed-identities.md)]