### YamlMime:ModuleUnit
uid: learn.wwl.implement-access-management-for-azure-resources.configure-azure-key-vault-rbac-policies
title: Configure Azure Key Vault RBAC policies
metadata:
  title: Configure Azure Key Vault RBAC policies
  description: "Configure Azure Key Vault RBAC policies"
  ms.date: 10/30/2023
  author: wwlpublish
  ms.author: roberts
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/7-configure-azure-key-vault-role-based-access-control-policies.md)]