### YamlMime:ModuleUnit
uid: learn.wwl.modify-data-with-transact-sql.automatic-values
title: Generate automatic values
metadata:
  title: Generate automatic values
  description: "Generate automatic values"
  ms.date: 04/29/2022
  author: wwlpublish
  ms.author: anrudduc
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/3-automatic-values.md)]