### YamlMime:ModuleUnit
uid: learn.wwl.design-network-solutions.design-for-application-delivery-services
title: Design for application delivery services
metadata:
  title: Design for application delivery services
  description: "Review considerations and a decision tree flowchart to design for application delivery services."
  ms.date: 12/09/2024
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 2
content: |
  [!include[](includes/7-design-for-application-delivery-services.md)]