### YamlMime:ModuleUnit
uid: learn.wwl.design-network-solutions.design-for-application-protection-services
title: Design for application protection services
metadata:
  title: Design for application protection services
  description: "Design for application protection services"
  ms.date: 12/09/2024
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/8-design-for-application-protection-services.md)]