### YamlMime:ModuleUnit
uid: learn.wwl.enroll-devices-use-endpoint-configuration-manager.monitor-configuration-manager-client
title: Monitor the Microsoft Configuration Manager client
metadata:
  title: Monitor the Microsoft Configuration Manager client
  description: "Monitor the Microsoft Configuration Manager client"
  ms.date: 04/22/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 3
content: |
  [!include[](includes/3-monitor-configuration-manager-client.md)]