### YamlMime:ModuleUnit
uid: learn.azure.build-api-azure-functions.7-query-azure-cosmos-db
title: Understand Azure Functions app settings
metadata:
  title: Understand Azure Functions app settings
  description: Understand Azure Functions app settings
  ms.date: 02/27/2024
  author: burkeholland
  ms.author: buhollan
  ms.topic: unit
  ms.custom: team=cloud_advocates
  ms.contributors: buhollan-12142020
durationInMinutes: 4
content: |
  [!include[](includes/5-app-settings.md)]
