### YamlMime:ModuleUnit
uid: learn.azure.build-api-azure-functions.8-exercise-query-azure-cosmos-db
title: Exercise - Add connection string to Azure Functions app settings
metadata:
  title: Exercise - Add connection string to Azure Functions app settings
  description: Exercise - Add connection string to Azure Functions app settings
  ms.date: 02/27/2024
  author: burkeholland
  ms.author: buhollan
  ms.topic: unit
  ms.custom: team=cloud_advocates
  ms.contributors: buhollan-12142020
interactive: bash
azureSandbox: true
durationInMinutes: 4
content: |
  [!include[](includes/6-exercise-app-settings.md)]
