### YamlMime:ModuleUnit
uid: learn.azure.build-api-azure-functions.5-rest-function-routes
title: REST and function routes
metadata:
  title: REST and function routes
  description: REST and function routes
  ms.date: 02/27/2024
  author: burkeholland
  ms.author: buhollan
  ms.topic: unit
  ms.custom: team=cloud_advocates
  ms.contributors: buhollan-12142020
durationInMinutes: 4
content: |
  [!include[](includes/7-rest-function-routes.md)]
