### YamlMime:ModuleUnit
uid: learn.azure.build-api-azure-functions.9-understand-cors
title: Configure CORS
metadata:
  title: Configure CORS
  description: Configure CORS
  ms.date: 02/27/2024
  author: burkeholland
  ms.author: buhollan
  ms.topic: unit
  ms.custom: team=cloud_advocates
  ms.contributors: buhollan-12142020
durationInMinutes: 3
content: |
  [!include[](includes/9-configure-cors.md)]
