### YamlMime:ModuleUnit
uid: learn.configure-dependabot-security-updates-on-github-repo.introduction
title: Introduction
metadata:
  unitType: introduction
  title: Introduction
  description: GitHub dependency management tools help you handle the security risks and maintenance requirements of incorporating third-party software into your project.
  ms.date: 04/25/2024
  author: a-a-ron
  ms.author: aastewar
  ms.topic: unit
durationInMinutes: 1
content: |
  [!include[](includes/1-introduction.md)]
