### YamlMime:ModuleUnit
uid: learn.configure-dependabot-security-updates-on-github-repo.manage-your-dependencies-github
title: Manage your dependencies on GitHub 
metadata:
  unitType: learning-content 
  title: Manage your dependencies on GitHub
  description: In this unit, you'll learn about the GitHub tools for managing your dependencies.
  ms.date: 04/25/2024
  author: a-a-ron
  ms.author: aastewar
  ms.topic: unit
durationInMinutes: 4
content: |
  [!include[](includes/2-manage-your-dependencies-github.md)]
