### YamlMime:ModuleUnit
uid: learn.configure-dependabot-security-updates-on-github-repo.dependabot-security-updates
title: Dependabot security updates
metadata:
  unitType: learning-content
  title: Dependabot security updates
  description: Dependabot security updates help you fix the vulnerabilities identified by Dependabot alerts and keep track of different versions of dependent packages.
  ms.date: 04/25/2024
  author: a-a-ron
  ms.author: aastewar
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/4-dependabot-security-updates.md)]
