### YamlMime:ModuleUnit
uid: learn.wwl.implement-windows-server-iscsi.configure-high-availability-for-iscsi
title: Configure high availability for iSCSI
metadata:
  title: Configure high availability for iSCSI
  description: "Configure high availability for iSCSI"
  ms.date: 04/15/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 5
content: |
  [!include[](includes/5-configure-high-availability-internet-small-computer-systems-interface.md)]