### YamlMime:ModuleUnit
uid: learn.create-aspire-application.learn-how-create-new-aspire-application
title: Learn how to create a new .NET Aspire project
metadata:
  title: Learn how to create a new .NET Aspire project
  description: "Learn how to create a new .NET Aspire project, understand the differences between the two project templates. Then explore the structure of the solutions generated."
  ms.date: 2/6/2024
  author: camsoper
  ms.author: casoper
  ms.topic: unit
  ms.custom: devx-track-dotnet
durationInMinutes: 5
content: |
  [!include[](includes/learn-how-create-new-aspire-application.md)]
