### YamlMime:ModuleUnit
uid: learn.wwl.manage-network-service-settings-for-windows-devices-use-powershell-cmdlets.manage-windows-firewall-settings-powershell
title: Manage Windows Firewall settings in PowerShell
metadata:
  title: Manage Windows Firewall settings in PowerShell
  description: "Manage Windows Firewall settings in PowerShell"
  ms.date: 10/20/2022
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/5-manage-windows-firewall-settings-powershell.md)]
