### YamlMime:ModuleUnit
uid: learn.wwl.respond-to-data-loss-prevention-alerts-microsoft-365.investigate-dlp-cloud-app-security
title: Investigate data loss prevention alerts in Microsoft Defender for Cloud Apps
metadata:
  title: Investigate data loss prevention alerts in Microsoft Defender for Cloud Apps
  description: "Investigate data loss prevention alerts in Microsoft Defender for Cloud Apps"
  ms.date: 08/15/2022
  author: wwlpublish
  ms.author: bneeb
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/4-investigate-data-loss-prevention-alerts-microsoft-cloud-app-security.md)]