### YamlMime:ModuleUnit
uid: learn.wwl.enforce-power-bi-model-security.exercise-enforce-model-security
title: 'Exercise: Enforce model security'
metadata:
  title: 'Exercise: Enforce model security'
  description: "Exercise: Enforce model security"
  ms.date: 09/25/2024
  author: angierudduck
  ms.author: anrudduc
  ms.topic: unit
azureSandbox: false
labId: 124444
labModal: false
durationInMinutes: 45
content: |
  [!include[](includes/4a-exercise-enforce-model-security.md)]