### YamlMime:ModuleUnit
uid: learn.azure.migrate-aspnet-app-azure-kubernetes-service.exercise-setup-host-environment
metadata:
  title: Exercise - Set up host environment
  description: Describes the steps to prepare Azure subscription and source application to be containerized.
  ms.date: 01/11/2023
  author: rmcmurray
  ms.author: robmcm
  ms.topic: unit
title: Exercise - Set up host environment
durationInMinutes: 10
content: |
  [!include[](includes/exercise-setup-host-environment.md)]