### YamlMime:ModuleUnit
uid: learn.fsharp-first-steps.fsharp-development-environment
title: F# development environment
metadata:
  unitType: learning-content
  title: "F# development environment"
  description: "Overview of tools to help you build F# applications"
  ms.date: 02/22/2023
  author: luisquintanilla
  ms.author: luquinta
  ms.manager: markl
  ms.topic: unit
  ms.custom:
    - devx-track-dotnet
durationInMinutes: 2
content: |
  [!include[](includes/3-fsharp-development-environment.md)]
