### YamlMime:ModuleUnit
uid: learn.wwl.configure-container-app-azure-container-apps.create-container-app-container-app-environment
title: Create a container app and container app environment
metadata:
  title: Create a container app and container app environment
  description: "Create a container app and container app environment"
  ms.date: 11/06/2024
  author: wwlpublish
  ms.author: cahowd
  ms.topic: unit
  ms.custom:
  - ai-learning-hub
durationInMinutes: 10
content: |
  [!include[](includes/4-create-container-app-container-app-environment.md)]