### YamlMime:ModuleUnit
uid: learn.wwl.deploy-manage-dhcp.use-dhcp-to-simplify-ip-configuration
title: Use DHCP to simplify IP configuration
metadata:
  title: Use DHCP to simplify IP configuration
  description: "Use DHCP to simplify IP configuration"
  ms.date: 04/15/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/2-use-dynamic-host-configuration-protocol-simplify-ip-configuration.md)]