### YamlMime:ModuleUnit
uid: learn.wwl.deploy-manage-dhcp.configure-dhcp-options
title: Configure DHCP options
metadata:
  title: Configure DHCP options
  description: "Configure DHCP options"
  ms.date: 04/15/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/4-configure-dynamic-host-configuration-protocol-options.md)]
quiz:
  title: "Quick review"
  questions:
  - content: "When considering DHCP options, which of the following has the highest precedence?"
    choices:
    - content: "Server level options"
      isCorrect: false
      explanation: "That's incorrect. These are general purpose options and are overridden by both scope and class level options."
    - content: "Class level options"
      isCorrect: true
      explanation: "That's correct. Class options override both scope and server options."
    - content: "Scope level options"
      isCorrect: false
      explanation: "That's incorrect. Scope options override server options, but not class level options."