### YamlMime:ModuleUnit
uid: learn.wwl.deploy-manage-dhcp.select-dhcp-high-availability-options
title: Select DHCP high availability options
metadata:
  title: Select DHCP high availability options
  description: "Select DHCP high availability options"
  ms.date: 04/15/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/6-select-dynamic-host-configuration-protocol-high-availability-options.md)]