### YamlMime:ModuleUnit
uid: learn.wwl.deploy-manage-dhcp.implement-dhcp-failover
title: Implement DHCP Failover
metadata:
  title: Implement DHCP Failover
  description: "Implement DHCP Failover"
  ms.date: 04/15/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/7-implement-dynamic-host-configuration-protocol-failover.md)]