### YamlMime:ModuleUnit
uid: learn.wwl.configure-integrate-analytics-agent-defender-cloud.configure-log-analytics-agent-workspace
title: Configure the Log Analytics agent and workspace
metadata:
  title: Configure the Log Analytics agent and workspace
  description: "Configure the Log Analytics agent and workspace"
  ms.date: 05/31/2024
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom: N/A, linux-related-content
durationInMinutes: 10
content: |
  [!include[](includes/3-configure-log-analytics-agent-workspace.md)]
