### YamlMime:ModuleUnit
uid: learn.wwl.configure-integrate-analytics-agent-defender-cloud.configure-integration-with-the-log-analytics-agent
title: Exercise - Configure and integrate a Log Analytics agent and workspace agent in Defender for Cloud
metadata:
  title: Exercise - Configure and integrate a Log Analytics agent and workspace agent in Defender for Cloud
  description: "Exercise - Configure and integrate a Log Analytics agent and workspace agent in Defender for Cloud"
  ms.date: 05/31/2024
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 30
content: |
  [!include[](includes/4-configure-integration-with-the-log-analytics-agent.md)]