### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-secure-microsoft-365.design-configurations-operational-practices-microsoft-365
title: Design configurations and operational practices for Microsoft 365
metadata:
  title: Design configurations and operational practices for Microsoft 365
  description: "This is a preparatory unit for SC-100 on the topic: design configurations and operational practices for Microsoft 365."
  ms.date: 3/14/2023
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/4-design-configurations-operational-practices-microsoft-365.md)]