### YamlMime:ModuleUnit
uid: learn.nvidia.nvidia-deepstream-embedded-device-deployment-azure.3-configure-deepstream-graph-publish-data-azure-iot-hub
title: Exercise - Configure DeepStream Graph Composer to publish data to Azure IoT Hub
metadata:
  title: Exercise - Configure DeepStream Graph Composer to publish data to Azure IoT Hub
  description: Exercise - Configure DeepStream Graph Composer to publish data to Azure IoT Hub.
  author: toolboc
  ms.author: chnoring
  ms.date: 11/09/2021
  ms.custom: team=nextgen
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/3-configure-deepstream-graph-publish-data-azure-iot-hub.md)]