### YamlMime:ModuleUnit
uid: learn.nvidia.nvidia-deepstream-embedded-device-deployment-azure.5-configure-azure-iot-edge-nvidia-embedded-hardware
title: Exercise - Configure Azure IoT Edge on NVIDIA embedded hardware
metadata:
  title: Exercise - Configure Azure IoT Edge on NVIDIA embedded hardware
  description: Exercise - Configure Azure IoT Edge on NVIDIA embedded hardware.
  author: toolboc
  ms.author: chnoring
  ms.date: 11/09/2021
  ms.custom: team=nextgen
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/5-configure-azure-iot-edge-nvidia-embedded-hardware.md)]