### YamlMime:ModuleUnit
uid: learn-wwl.secure-responsible-conversational-ai.bot-security
title: Handle data securely
metadata:
  title: Handle data securely
  description: Ensuring that your bot is secure from malicious attacks should be of high priority when designing and developing it. This section provides guidelines on how to make sure you protect your application and your user's security.
  ms.date: 02/20/2020
  author: Adriamen
  ms.author: japerena
  ms.topic: unit
durationInMinutes: 7
content: |
  [!include[](includes/6-bot-security.md)] 