### YamlMime:ModuleUnit
uid: learn.wwl.manage-azure-stack-hci-clusters.configure-cluster-quorum
title: Configure an Azure Stack HCI cluster quorum
metadata:
  title: Configure an Azure Stack HCI cluster quorum
  description: "Configure an Azure Stack HCI cluster quorum"
  ms.date: 06/09/2021
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
durationInMinutes: 14
content: |
  [!include[](includes/5-configure-cluster-quorum.md)]
quiz:
  title: "Knowledge check"
  questions:
  - content: "Contoso datacenters have reliable, resilient connectivity to Azure regions in the East US region. You need to recommend a cluster witness for Contoso's Azure Stack HCI deployments. Which witness type should you recommend?"
    choices:
    - content: "Cloud witness"
      isCorrect: true
      explanation: "Correct. Cloud witness is the recommended option for configuring a cluster witness because the cluster has reliable network connectivity to the Azure region hosting the storage account."
    - content: "File share witness"
      isCorrect: false
      explanation: "Incorrect. Although you can configure the cluster witness either as a file share or as a blob in an Azure Storage account, we recommend the latter as long as the cluster has reliable network connectivity to the Azure region hosting the storage account."
    - content: "Disk witness"
      isCorrect: false
      explanation: "Incorrect. Azure Stack HCI does not support disk witness."