### YamlMime:ModuleUnit
uid: learn.wwl.configure-web-app-settings.configure-general-settings
title: Configure general settings
metadata:
  title: Configure general settings
  description: "Configure general settings"
  ms.date: 06/11/2024
  author: wwlpublish
  ms.author: jeffko
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 4
content: |
  [!include[](includes/3-configure-general-settings.md)]