### YamlMime:ModuleUnit
uid: learn.wwl.configure-web-app-settings.configure-security-certificates
title: Configure security certificates
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure security certificates
  description: "Configure security certificates"
  ms.date: 02/11/2025
  author: wwlpublish
  ms.author: jeffko
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 4
content: |
  [!include[](includes/6-configure-security-certificates.md)]