### YamlMime:ModuleUnit
uid: learn.wwl.design-implement-hybrid-networking.exercise-create-configure-local-network-gateway
title: 'Exercise: Create and configure a virtual network gateway'
metadata:
  title: 'Exercise: Create and configure a virtual network gateway'
  description: "Exercise: Create and configure a virtual network gateway"
  ms.date: 11/21/2024
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
  ms.custom:
  - N/A
azureSandbox: false
labModal: false
durationInMinutes: 10
content: |
  [!include[](includes/3-exercise-create-configure-local-network-gateway.md)]