### YamlMime:ModuleUnit
uid: learn.student-evangelism.node-web-routes.manage-routes
title: Understand URLs and routes
metadata:
  title: Understand URLs and routes
  description: Divide your application into sections for the different resources.
  author: diberry
  ms.author: diberry
  ms.date: 01/30/2024
  ms.topic: unit
durationInMinutes: 7
content: |
  [!include[](includes/2-manage-routes.md)]
