### YamlMime:ModuleUnit
uid: learn.use-docker-container-dev-env-vs-code.2-use-as-dev-env
title: Use the Dev Containers extension in Visual Studio Code
metadata:
  title: Use the Dev Containers extension in Visual Studio Code
  description: Get an overview of the Dev Containers extension in Visual Studio Code and the files it adds to your project.
  ms.date: 04/28/2023
  author: bamurtaugh
  ms.author: brmurtau
  ms.topic: unit
  ms.custom: devdivchpfy22
durationInMinutes: 2
content: |
  [!include[](includes/3-use-as-development-environment.md)]
  