### YamlMime:ModuleUnit
uid: learn.use-docker-container-dev-env-vs-code.6-customize-settings
title: Customize project and editor settings 
metadata:
  title: Customize project and editor settings 
  description: Learn how to customize settings for your project and editor through the devcontainer.json file.
  ms.date: 04/28/2023
  author: bamurtaugh
  ms.author: brmurtau
  ms.topic: unit
  ms.custom: devdivchpfy22
durationInMinutes: 3
content: |
  [!include[](includes/5-customize-settings.md)]
  