### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-fslogix.configure-profile-containers
title: Configure Profile Containers
metadata:
  title: Configure Profile Containers
  description: "Configure Profile Containers"
  ms.date: 06/13/2023
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 10
content: |
  [!include[](includes/10-configure-profile-containers.md)]