### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-fslogix.manage-rule-sets-application-masking
title: Manage Rule Sets and application masking
metadata:
  title: Manage Rule Sets and application masking
  description: "Manage Rule Sets and application masking"
  ms.date: 06/13/2023
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 9
content: |
  [!include[](includes/12-manage-rule-sets-application-mask.md)]