### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-fslogix.configure-office-containers
title: Configure Office Containers
metadata:
  title: Configure Office Containers
  description: "Configure Office Containers"
  ms.date: 06/13/2023
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/7-configure-office-containers.md)]