### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-fslogix.configure-profile-containers
title: Using FSLogix Apps RuleEditor and Rule Sets
metadata:
  title: Using FSLogix Apps RuleEditor and Rule Sets
  description: "Using FSLogix Apps RuleEditor and Rule Sets"
  ms.date: 08/07/2024
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 9
content: |
  [!include[](includes/7-configure-profile-containers.md)]