### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-fslogix.install-microsoft-office-fslogix-application-containers
title: Installing Microsoft Office using FSLogix application containers
metadata:
  title: Installing Microsoft Office using FSLogix application containers
  description: "Installing Microsoft Office using FSLogix application containers"
  ms.date: 06/13/2023
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/8-install-microsoft-office-fslogix-application-containers.md)]