### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-fslogix.configure-cloud-cache
title: Configure Cloud Cache
metadata:
  title: Configure Cloud Cache
  description: "Configure Cloud Cache"
  ms.date: 06/13/2023
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/9-configure-cloud-cache.md)]