### YamlMime:ModuleUnit
uid: learn.wwl.continuous-deployment-for-machine-learning.set-up-environments-for-development-production
title: Set up environments for development and production
metadata:
  title: Set up environments for development and production
  description: "Set up environments for development and production"
  ms.date: 08/05/2022
  author: wwlpublish
  ms.author: madiepev
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 10
content: |
  [!include[](includes/2-set-up-environments-for-development-production.md)]