### YamlMime:ModuleUnit
uid: learn.wwl.continuous-deployment-for-machine-learning.control-deployments-approval-gates
title: Control deployments with approval gates
metadata:
  title: Control deployments with approval gates
  description: "Control deployments with approval gates"
  ms.date: 08/05/2022
  author: wwlpublish
  ms.author: madiepev
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/3-control-deployments-approval-gates.md)]