### YamlMime:ModuleUnit
uid: learn.azure.data-classification-and-data-protection.6-what-microsoft-cloud-app-security
title: Microsoft Defender for Cloud Apps
metadata:
  title: Learn about the features and capabilities of the Microsoft Defender for Cloud Apps cloud access security broker (CASB).
  description: Microsoft Defender for Cloud Apps
  ms.date: 08/08/2023
  author: cwatson-cat
  ms.author: cwatson
  ms.topic: unit
durationInMinutes: 6
content: |
  [!include[](includes/6-what-microsoft-cloud-app-security.md)]
