### YamlMime:ModuleUnit
uid: learn.oxford.develop-secure-iot-solutions-for-azure-sphere.exercise-azure-rtos-environment
title: Exercise - Deploy an Azure RTOS real-time sensor application to monitor the room environment
metadata:
  title: Exercise - Deploy an Azure RTOS real-time sensor application to monitor the room environment
  description: In this section, we will deploy an Azure RTOS real-time sensor application to monitor the room environment
  ms.date: 11/10/2020
  author: leestott
  ms.author: leestott
  ms.topic: unit
  ms.custom: team=nextgen
  ms.service: iot-central
durationInMinutes: 5 # dummy number at present
content: |
  [!include[](includes/14-exercise-azure-rtos-environment.md)]
