### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-enforcement-cloud-governance-policies.configure-azure-blueprints
title: Configure security settings by using Azure Blueprint
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure security settings by using Azure Blueprint
  description: "Configure security settings by using Azure Blueprint"
  ms.date: 02/05/2025
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/6-configure-azure-blueprints.md)]