### YamlMime:ModuleUnit
uid: learn.wwl.execute-mobile-application-management.examine-considerations-mobile-application-management
title: Examine considerations for mobile application management
metadata:
  title: Examine considerations for mobile application management
  description: "Examine considerations for mobile application management"
  ms.date: 07/18/2023
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/3-examine-considerations-mobile-application-management.md)]