### YamlMime:ModuleUnit
uid: learn.wwl.execute-mobile-application-management.manage-mobile-application-management-policies-intune
title: Manage mobile application management policies in Intune
metadata:
  title: Manage mobile application management policies in Intune
  description: "Manage mobile application management policies in Intune"
  ms.date: 07/18/2023
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/6-manage-mobile-application-management-policies-intune.md)]