### YamlMime:ModuleUnit
uid: learn.wwl.microsoft-defender-cloud-security-posture.connect-hybrid-cloud-multi-cloud-environments
title: Connect hybrid cloud and multicloud environments to Microsoft Defender for Cloud
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Connect hybrid cloud and multicloud environments to Microsoft Defender for Cloud
  description: "Connect hybrid cloud and multicloud environments to Microsoft Defender for Cloud"
  ms.date: 02/07/2025
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/7-connect-hybrid-cloud-multi-cloud-environments.md)]