### YamlMime:ModuleUnit
uid: learn.quantum.quantum-software-applications.applications
title: Applications
metadata:
  title: Applications
  description: This unit focuses on the application layer to solve specific problems using quantum algorithms. 
  ms.date: 10/01/2024
  author: a-a-ron
  ms.author: aastewar
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/3-applications.md)]