### YamlMime:ModuleUnit
uid: learn.wwl.design-application-architecture.design-automated-app-deployment-solution
title: Design an automated app deployment solution
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Design an automated app deployment solution
  description: "Design an automated app deployment solution"
  ms.date: 01/29/2025
  author: wwlpublish
  ms.author: cynthist
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 6
content: |
  [!include[](includes/8-design-automated-app-deployment-solution.md)]