### YamlMime:ModuleUnit
uid: learn.wwl.design-resiliency-strategy-common-cyberthreats-like-ransomware.configurations-secure-backup-restore
title:  Design solutions for business continuity and disaster recovery (BCDR), including secure backup and restore
metadata:
  title:  Design solutions for business continuity and disaster recovery (BCDR), including secure backup and restore
  description: "Learn how to design solutions for business continuity and disaster recovery (BCDR), including secure backup and restore."
  ms.date: 5/17/2024
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/4-configurations-secure-backup-restore.md)]