### YamlMime:ModuleUnit
uid: learn.wwl.get-started-identity-access-labs.configure-password-protection
title: Perform basic password protection tasks
metadata:
  title: Perform basic password protection tasks
  description: "Perform an interactive lab to configure and enable password protection features."
  ms.date: 03/27/2025
  author: wwlpublish
  ms.author: roberts
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/4-configure-password-protect.md)]