### YamlMime:ModuleUnit
uid: learn.app-management-using-microsoft-endpoint-manager.3-app-configuration
title: Learn about configuring apps
metadata:
  title: Learn about configuring apps
  description: Learn about configuring apps with Microsoft Intune.
  ms.date: 10/23/2023
  author: Erikre
  ms.author: erikre
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/3-app-configuration.md)]
  
