### YamlMime:ModuleUnit
uid: learn.azdo.manage-delivery-plans.4-set-up-environment
title: Exercise - Set up your environment
metadata:
  title: Exercise - Set up your environment
  description: Create your Azure DevOps project.
  ms.date: 10/06/2023
  ms.custom: devdivchpfy22
  author: chcomley
  ms.author: chcomley
  ms.topic: unit
durationInMinutes: 4
content: |
  [!include[](includes/4-set-up-environment.md)]
