### YamlMime:ModuleUnit
uid: learn.azdo.manage-delivery-plans.7-clean-up-environment
title: Exercise - Clean up your environment
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Exercise - Clean up your environment
  description: Clean up your Azure DevOps project.
  ms.date: 10/18/2024
  author: chcomley
  ms.author: chcomley
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/7-clean-up-environment.md)]

