### YamlMime:ModuleUnit
uid: learn.wwl.design-data-storage-solution-for-non-relational-data.design-for-storage-security
title: Design for storage security
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Design for storage security
  description: "Design for storage security"
  ms.date: 09/02/2024
  author: wwlpublish
  ms.author: cynthist
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 5
content: |
  [!include[](includes/8-design-for-storage-security.md)]
