### YamlMime:ModuleUnit
uid: learn.wwl.design-data-storage-solution-for-non-relational-data.design-for-storage-security
title: Design for storage security
metadata:
  title: Design for storage security
  description: "Design for storage security"
  ms.date: 12/10/2024
  author: wwlpublish
  ms.author: cynthist
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 6
content: |
  [!include[](includes/8-design-for-storage-security.md)]