### YamlMime:ModuleUnit
uid: learn.wwl.explore-azure-storage.examine-sap-hana-azure-virtual-machine-storage-configurations
title: Examine SAP HANA Azure Virtual Machine storage configurations
metadata:
  title: Examine SAP HANA Azure Virtual Machine storage configurations
  description: "Examine SAP HANA Azure Virtual Machine storage configurations."
  ms.date: 03/26/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/15-examine-sap-hana-azure-virtual-machine-storage-configurations.md)]