### YamlMime:ModuleUnit
uid: learn.wwl.explore-azure-storage.ultra-disk-storage-configuration-for-sap-hana
title: Explore Azure Ultra disk storage configuration for SAP HANA
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Explore Azure Ultra disk storage configuration for SAP HANA
  description: "Explore Azure Ultra disk storage configuration for SAP HANA, where the disk capabilities aren't bound to the disk size."
  ms.date: 08/13/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 4
content: |
  [!include[](includes/17-explore-azure-ultra-disk-storage-configuration-sap-hana.md)]
