### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.create-azure-iot-central-application
title: Exercise - Create an Azure IoT Central application
sandbox: true
metadata:
  title: Exercise - Create an Azure IoT Central application
  description: This content is a part of Build your first Azure IoT Central application to manage your coffee machines
  ms.date: 06/14/2023
  author: asergaz
  ms.author: sergaz
  ms.reviewer: adchukwu
  manager: lizross
  ms.custom: engagement-fy23
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/2-create-azure-iot-central-application.md)]