### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.configure-rules-actions
title: Exercise - Configure rules and actions to monitor your coffee machine
sandbox: true
interactive: bash
metadata:
  title: Exercise - Configure rules and actions to monitor your coffee machine
  description: This content is a part of Build your first Azure IoT Central application to manage your coffee machines
  ms.date: 06/14/2023
  author: asergaz
  ms.author: sergaz
  ms.reviewer: adchukwu
  manager: lizross
  ms.custom: engagement-fy23
  ms.topic: unit
durationInMinutes: 6
content: |
  [!include[](includes/8-configure-rules-actions.md)]