### YamlMime:ModuleUnit
uid: learn.create-saas-offer-commercial-marketplace.4-saas-offer-technical-configuration
title: SaaS offer technical configuration
metadata:
  title: SaaS offer technical configuration
  description: In this unit, we go over the technical information required to publish a transact software as a service (SaaS) offer.
  ms.date: 04/26/2024
  author: SindhuRaghvan
  ms.author: siraghav
  ms.topic: unit
durationInMinutes: 7
content: |
  [!include[](includes/4-saas-offer-technical-configuration.md)]
