### YamlMime:ModuleUnit
uid: learn.wwl.perform-backups-restores.explore-application-backup
title: Explore application backup
metadata:
  title: Explore application backup
  description: "Explore how Azure Backup completes a backup for Azure Virtual Machines hosting SAP applications."
  ms.date: 07/29/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 8
content: |
  [!include[](includes/4-explore-application-backup.md)]