### YamlMime:ModuleUnit
uid: learn.wwl.monitor-fabric-items.configure-alerts
title: Use delta tables with streaming data
metadata:
  title: Use delta tables with streaming data
  description: "Use delta tables with streaming data"
  ms.date: 11/14/2024
  author: JamesHerring
  ms.author: jamesh
  ms.topic: unit
  ms.custom:
  - fabric
durationInMinutes: 5
content: |
  [!include[](includes/5-configure-alerts.md)]