### YamlMime:ModuleUnit
uid: learn.wwl.monitor-fabric-items.configure-alerts
title: Optimize alerting using Activator
metadata:
  title: Optimize alerting using Activator
  description: "Optimize alerting using Activator
  ms.date: 11/14/2024
  author: JamesHerring
  ms.author: jamesh
  ms.topic: unit
  ms.custom:
  - fabric
durationInMinutes: 5
content: |
  [!include[](includes/5-configure-alerts.md)]