### YamlMime:ModuleUnit
uid: learn.wwl.monitor-fabric-items.exercise-configure-alerts-in-fabric
title: Exercise - Configure Alerts in Microsoft Fabric
metadata:
  title: Exercise - Configure Alerts in Microsoft Fabric
  description: "Exercise - Configure Alerts in Microsoft Fabric"
  ms.date: 11/14/2024
  author: JamesHerring
  ms.author: jamesh
  ms.topic: unit
  ms.custom:
  - fabric
durationInMinutes: 40
content: |
  [!include[](includes/6-exercise-configure-alerts-in-fabric.md)]