### YamlMime:ModuleUnit
uid: learn.wwl.connect-syslog-data-sources-to-azure-sentinel.configure-log-analytics-agent
title: Configure the Data Collection Rule for Syslog Data Sources
metadata:
  title: Configure the Data Collection Rule for Syslog Data Sources
  description: "Configure the Data Collection Rule for Syslog Data Sources"
  ms.date: 06/27/2022
  author: wwlpublish
  ms.author: kelawson
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/4-configure-log-analytics-agent.md)]