### YamlMime:ModuleUnit
uid: learn.sports-machine-learning.use-mixed-reality-toolkit.configure-unity-for-toolkit
metadata:
  title: Configure Unity for Windows Mixed Reality development
  description: Configure Unity for Windows Mixed Reality development.
  ms.date: 06/15/2021
  author: aprilspeight
  ms.author: apspeigh
  ms.topic: unit
  ms.custom: team=nextgen
title: Configure Unity for Windows Mixed Reality development
durationInMinutes: 10
content: |
  [!include[](includes/3-configure-unity-for-toolkit.md)]
