### YamlMime:ModuleUnit
uid: learn.wwl.customize-indexes-azure-cosmos-db-sql-api.exercise-configure-containers-index-policy-portal
title: "Exercise: Configure an Azure Cosmos DB for NoSQL container's index policy with the portal"
metadata:
  title: "Exercise: Configure an Azure Cosmos DB for NoSQL container's index policy with the portal"
  description: "Exercise: Configure an Azure Cosmos DB for NoSQL container's index policy with the portal"
  ms.date: 10/17/2022
  author: wwlpublish
  ms.author: calopez
  ms.topic: unit
azureSandbox: false
labId: 107581
labModal: true
durationInMinutes: 15
content: |
  [!include[](includes/4-exercise-configure-containers-index-policy-portal.md)]