### YamlMime:ModuleUnit
uid: learn.azure.build-first-azure-developer-cli-template.configure-cicd
title: Configure the CI/CD pipeline
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  unitType: learning-content
  title: Configure the CI/CD pipeline
  description: Configure the CI/CD pipeline for the template
  ms.date: 07/02/2024
  author: alexwolfmsft
  ms.author: alexwolf
  ms.topic: unit
  ms.custom: engagement-fy23
durationInMinutes: 2
content: |
  [!include[](includes/7-configure-cicd.md)]

