### YamlMime:ModuleUnit
uid: learn.dotnet-maui.create-user-interface-xaml.platform-specific-values-xaml
title: Platform-specific values in XAML 
metadata:
  unitType: unit 
  title: "Platform-specific values in XAML"
  description: "Describe how to fine-tune the UI for different platforms"
  ms.date: 10/13/2023
  author: codemillmatt  
  ms.author: masoucou
  ms.manager: markl
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/7-platform-specific-values-xaml.md)]
quiz:
  title: Knowledge check
  questions:
  - content: "Which markup extension can you use in your XAML code to detect the platform on which the app is running?"
    choices:
    - content: "`DevicePlatform`"
      isCorrect: false
      explanation: "No. `DevicePlatform` is a property of the DeviceInfo class, intended for use in C# code. Use the `OnPlatform` markup extension in your XAML code."
    - content: "`DeviceInfo`"
      isCorrect: false
      explanation: "No. The `DeviceInfo` is intended for use in C# code. Use the `OnPlatform` markup extension in your XAML code."
    - content: "`OnPlatform`"
      isCorrect: true
      explanation: "This is the correct answer."
  - content: "What is the purpose of the `TypeArguments` attribute for the `OnPlatform` extension?"
    choices:
    - content: "It specifies the type parameter for the extension, and ensures that the correct type of extension is created."
      isCorrect: true
      explanation: "This is the correct answer."
    - content: "It specifies the type of the platform on which the app is running"
      isCorrect: false
      explanation: "No. It specifies the type parameter for the extension."
    - content: "It enables you to specify the property to be set with a platform-specific value."
      isCorrect: false
      explanation: "No. It specifies the type parameter for the extension."

