### YamlMime:ModuleUnit
uid: learn.wwl.deploy-windows-server.use-wds-to
title: Use WDS to deploy Windows Server
metadata:
  title: Use WDS to deploy Windows Server
  description: "Use WDS to deploy Windows Server"
  ms.date: 02/26/2021
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
durationInMinutes: 10
content: |
  [!include[](includes/7-use-windows-deployment-services.md)]
quiz:
  title: "Quick review"
  questions:
  - content: "Which of the following components in WDS is responsible for handling multicast communications?"
    choices:
    - content: "The deployment server"
      isCorrect: false
      explanation: "That's incorrect. The deployment server uses the multicasting engine that the transport server component provides, to push operating system images across the network."
    - content: "The transport server"
      isCorrect: true
      explanation: "That's correct. The transport server component provides the core networking functionality of WDS for multicast transmission."
    - content: "Multicast is not supported in WDS, so this component is not present"
      isCorrect: false
      explanation: "That's incorrect. Multicasting is the means by which WDS communicates with devices."