### YamlMime:ModuleUnit
uid: learn.java-on-azure-container-apps.2-prepare-spring-boot-application
title: Prepare Spring Boot application
metadata:
  title: Prepare Spring Boot application
  description: Learn about application rediness before deploying to Azure Container Apps.
  author: hangwan
  ms.author: hangwan
  ms.date: 10/22/2024
  ms.topic: unit
  ms.custom:
    - team=cloud_advocates
    - devx-track-extended-java
  ms.contributors: hangwan97
durationInMinutes: 5
content: |
  [!include[](includes/2-prepare-spring-boot-application.md)]
