### YamlMime:ModuleUnit
uid: learn.java-on-azure-container-apps.3-deploy-spring-boot-application
title: Deploy Spring Boot application
metadata:
  title: Deploy Spring Boot application
  description: This unit presents the deployment of the Spring Boot application to Azure Container Apps.
  author: hangwan
  ms.author: hangwan
  ms.date: 10/22/2024
  ms.topic: unit
  ms.custom:
    - team=cloud_advocates
    - devx-track-extended-java
  ms.contributors: hangwan97
durationInMinutes: 5
content: |
  [!include[](includes/3-deploy-spring-boot-application.md)]
