### YamlMime:AchievementDetail
achievementUid: learn.introduction-azure-web-application-firewall.badge
metadata:
  title: >-
    Microsoft Badge: Introduction to Azure Web Application Firewall was issued
    by Microsoft
socialImageUrl: >-
  /training/achievements/introduction-to-azure-web-application-firewall-social.svg
