### YamlMime:AchievementDetail
achievementUid: learn.wwl.configure-validate-permissions.badge
metadata:
  title: 'Microsoft Badge: Configure and validate permissions was issued by Microsoft'
socialImageUrl: /training/achievements/generic-trophy-social.png
