### YamlMime:AchievementDetail
achievementUid: learn.aks-manage-application-state.badge
metadata:
  title: >-
    Microsoft Badge: Deploy and manage a stateful application by using Azure
    Cosmos DB and Azure Kubernetes Service was issued by Microsoft
socialImageUrl: /training/achievements/aks-manage-application-state.png
