### YamlMime:AchievementDetail
achievementUid: learn.wwl.configure-azure-active-directory.badge
metadata:
  title: 'Microsoft Badge: Configure Microsoft Entra ID was issued by Microsoft'
socialImageUrl: /training/achievements/azure-active-directory-social.png
