### YamlMime:AchievementDetail
achievementUid: learn.wwl.guided-project-configure-secure-access-workloads.badge
metadata:
  title: >-
    Microsoft Badge: Guided Project - Configure secure access to workloads with
    Azure virtual networking services was issued by Microsoft
socialImageUrl: /training/achievements/generic-badge-social.png
