### YamlMime:AchievementDetail
achievementUid: learn.wwl.configure-secure-access-pipeline-resources.badge
metadata:
  title: >-
    Microsoft Badge: Configure secure access to pipeline resources was issued by
    Microsoft
socialImageUrl: /training/achievements/generic-trophy-social.png
