### YamlMime:AchievementDetail
achievementUid: learn.wwl.case-study-design-security-solutions-applications-data.badge
metadata:
  title: >-
    Microsoft Badge: Case study: Design security solutions for applications and
    data was issued by Microsoft
socialImageUrl: /training/achievements/generic-badge-social.png
