### YamlMime:AchievementDetail
achievementUid: learn.wwl.configure-pipelines-securely-use-variables-parameters.badge
metadata:
  title: >-
    Microsoft Badge: Configure pipelines to securely use variables and
    parameters was issued by Microsoft
socialImageUrl: /training/achievements/generic-trophy-social.png
