### YamlMime:AchievementDetail
achievementUid: learn.wwl.design-solutions-security-posture-management-hybrid-multicloud-environments.badge
metadata:
  title: >-
    Microsoft Badge: Design solutions for securing privileged access was issued
    by Microsoft
socialImageUrl: /training/achievements/design-solutions-posture-management-hybrid-multicloud-environments-social.png
