### YamlMime:AchievementDetail
achievementUid: learn.azure.automate-virtual-machine-software-installation-configuration.badge
metadata:
  title: >-
    Microsoft Badge: Automate the installation and configuration of software in
    your Virtual Machines was issued by Microsoft
socialImageUrl: >-
  /training/achievements/automate-virtual-machine-software-installation-configuration.png
