### YamlMime:AchievementDetail
achievementUid: learn.wwl.configure-secure-access-azure-repos-from-pipelines.badge
metadata:
  title: >-
    Microsoft Badge: Configure secure access to Azure Repos from pipelines was
    issued by Microsoft
socialImageUrl: /training/achievements/generic-trophy-social.png
