### YamlMime:AchievementDetail
achievementUid: learn.aks-secrets-configure-app.badge
metadata:
  title: >-
    Microsoft Badge: Manage Application Configuration and Secrets in Azure
    Kubernetes Service (AKS) was issued by Microsoft
socialImageUrl: /training/achievements/aks-secrets-configure-app.png
