### YamlMime:AchievementDetail
achievementUid: learn.wwl.configure-secure-workloads-using-azure-virtual-networking.trophy
metadata:
  title: >-
    Microsoft Trophy: Configure secure access to your workloads using Azure
    virtual networking was issued by Microsoft
socialImageUrl: /training/achievements/generic-trophy-social.png
