### YamlMime:AchievementDetail
achievementUid: learn.azure.azure-netapp-files-application-volume-group.badge
metadata:
  title: >-
    Microsoft Badge: Using Azure NetApp Files application volume group was issued by Microsoft
socialImageUrl: /training/achievements/introduction-to-azure-netapp-files-social.png
