### YamlMime:AchievementDetail
achievementUid: >-
  learn.wwl.configure-project-repository-structure-support-secure-pipelines.badge
metadata:
  title: >-
    Microsoft Badge: Configure a project and repository structure to support
    secure pipelines was issued by Microsoft
socialImageUrl: /training/achievements/generic-trophy-social.png
