### YamlMime:AchievementDetail
achievementUid: learn.wwl.implement-azure-app-configuration.badge
metadata:
  title: 'Microsoft Badge: Implement Azure App Configuration was issued by Microsoft'
socialImageUrl: /training/achievements/azure-app-implement-configuration-social.png
