### YamlMime:ModuleUnit
uid: learn.introduction-to-application-resiliency-azure.introduction-to-application-resiliency-in-azure
title: Introduction to application resiliency in Azure
metadata:
  title: Introduction to application resiliency in Azure
  description: TBD
  ms.date: 08/14/2024
  author: Orin-Thomas
  ms.author: orthomas
  ms.topic: unit
durationInMinutes: 1
content: |
  [!include[](includes/1-introduction-to-application-resiliency-in-azure.md)]
