### YamlMime:ModuleUnit
uid: learn.student-evangelism.web-development-101.functions.return-values
title: Return values
metadata:
  title: Return values
  description: Functions can return values, which is great when you want to allow functions to perform calculations or other operations that return results. In this unit, you learn how to use return values in JavaScript functions.
  author: GeekTrainer
  ms.author: chnoring
  ms.date: 01/26/2023
  ms.topic: unit
  ms.custom:
    - team=nextgen
    - devx-track-js
durationInMinutes: 2
content: |
  [!include[](includes/4-return-values.md)]
