### YamlMime:ModuleUnit
uid: learn.wwl.configure-network-routing-endpoints.identify-user-defined-routes
title: Identify user-defined routes
metadata:
  title: Identify user-defined routes
  description: "Identify how to work with user-defined routes and next hop targets."
  ms.date: 06/14/2024
  author: wwlpublish
  ms.author: cynthist
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/3-identify-user-defined-routes.md)]