### YamlMime:ModuleUnit
uid: learn.wwl.configure-databases-for-optimal-performance.describe-database-scoped-configuration-options
title: Describe database scoped configuration options
metadata:
  title: Describe database scoped configuration options
  description: "Describe database scoped configuration options"
  ms.date: 05/05/2022
  author: wwlpublish
  ms.author: jupadrao
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/3-describe-database-scoped-configuration-options.md)]