### YamlMime:ModuleUnit
uid: learn.student-evangelism.python-flask-build-ai-web-app.1-exercise-set-up-environment
title: Exercise - Set up a development environment
metadata:
  title: Exercise - Set up a development environment
  description: In this exercise, you set up a development environment for building websites by using Flask and Python.
  ms.date: 04/08/2022
  author: acomfort248
  ms.author: chnoring
  ms.topic: unit
  ms.custom:
    - team=nextgen
    - devx-track-python
durationInMinutes: 15
content: |
  [!include[](includes/1-exercise-set-up-environment.md)]
