### YamlMime:ModuleUnit
uid: learn.languages.aspnetcore-accessibility.3-exercise-create-sample-application
metadata:
  title: Exercise - Create the sample application
  description: Create a sample ASP.NET Core web application that has common accessibility issues.
  ms.date: 02/13/2024
  author: jongalloway
  ms.author: jogallow
  ms.manager: markl
  ms.topic: unit
  
title: Exercise - Create the sample application
durationInMinutes: 5
content: |
  [!include[](includes/3-exercise-create-sample-application.md)]
