### YamlMime:ModuleUnit
uid: learn.wwl.manage-defender-endpoint.explore-application-guard
title: Explore Microsoft Defender Application Guard
metadata:
  title: Explore Microsoft Defender Application Guard
  description: "Explore Microsoft Defender Application Guard"
  ms.date: 04/23/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 4
content: |
  [!include[](includes/5-explore-application-guard.md)]