### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Configure Azure Cache for Redis
metadata:
  title: Configure Azure Cache for Redis
  description: Configure Azure Cache for Redis
  ms.date: 03/11/2024
  author: flang-msft
  ms.author: franlanglois
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/3-configure-redis-cache.md)]
