### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: Exercise - Set environment variables
  description: Set environment variables in Azure Container Instances.
  ms.date: 04/03/2024
  author: v-tcassi
  ms.author: tomcassidy
  ms.topic: unit
  ms.custom: devx-track-azurecli
title: Exercise - Set environment variables
durationInMinutes: 10
content: |
  [!include[](includes/4-use-environment-variables.md)]
