### YamlMime:ModuleUnit
uid: learn.build-app-with-scale-sets.exercise-configure-virtual-machine-scale-set
title: Exercise - Configure a Virtual Machine Scale Set

metadata:
  title: Exercise - Configure a Virtual Machine Scale Set
  description: Exercise - Configure a Virtual Machine Scale Set
  ms.date: 04/03/2024
  author: ju-shim
  ms.author: jushiman
  ms.reviewer: mimckitt
  ms.topic: unit

durationInMinutes: 10
azureSandbox: false
content: |
  [!include[](includes/5-exercise-configure-virtual-machine-scale-set.md)]
