### YamlMime:ModuleUnit
uid: learn.wwl.load-balancing-https-traffic-azure.design-azure-application-gateway
title: Design Azure Application Gateway
metadata:
  title: Design Azure Application Gateway
  description: "Design Azure Application Gateway"
  ms.date: 08/01/2024
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/2-design-azure-application-gateway.md)]