### YamlMime:ModuleUnit
uid: learn.wwl.load-balancing-https-traffic-azure.design-azure-application-gateway
title: Design Azure Application Gateway
metadata:
  title: Design Azure Application Gateway
  description: "Design Azure Application Gateway"
  ms.date: 07/11/2023
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/2-design-azure-application-gateway.md)]