### YamlMime:ModuleUnit
uid: learn.wwl.load-balancing-https-traffic-azure.exercise-deploy-azure-application-gateway
title: 'Exercise: deploy Azure Application Gateway'
metadata:
  title: 'Exercise: deploy Azure Application Gateway'
  description: "Exercise: deploy Azure Application Gateway"
  ms.date: 07/11/2023
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
durationInMinutes: 8
content: |
  [!include[](includes/4-exercise-deploy-azure-application-gateway.md)]