### YamlMime:ModuleUnit
uid: learn.wwl.security-virtual-networks.secure-paas-deployments
title: Configure firewall settings on PaaS resources
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure firewall settings on PaaS resources
  description: "Configure firewall settings on PaaS resources"
  ms.date: 02/21/2025
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/12-secure-paas-deployments.md)]