### YamlMime:ModuleUnit
uid: learn.wwl.security-virtual-networks.azure-best-practices-for-network-security
title: Configure firewall settings on Azure resources
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure firewall settings on Azure resources
  description: "Configure firewall settings on Azure resources"
  ms.date: 02/21/2025
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/15-azure-best-practices-for-network-security.md)]