### YamlMime:ModuleUnit
uid: learn.wwl.security-virtual-networks.mcsb-data-protection-logging-threat-detection-network-security
title: 'MCSB Security Controls: MCSB Security Controls: Data Protection, Logging and Threat Detection, and Network Security'
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: 'MCSB Security Controls: MCSB Security Controls: Data Protection, Logging and Threat Detection, and Network Security'
  description: "MCSB Security Controls: MCSB Security Controls: Data Protection, Logging and Threat Detection, and Network Security"
  ms.date: 02/21/2025
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 15
content: |
  [!include[](includes/3-mcsb-data-protection-logging-threat-detection-network-security.md)]