### YamlMime:ModuleUnit
uid: learn.wwl.manage-azure-virtual-desktop.configure-azure-virtual-desktop
title: Configure Azure Virtual Desktop
metadata:
  title: Configure Azure Virtual Desktop
  description: "Configure Azure Virtual Desktop"
  ms.date: 05/14/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 9
content: |
  [!include[](includes/4-configure-azure-virtual-desktop.md)]