### YamlMime:ModuleUnit
uid: learn.wwl.unlock-insights-microsoft-copilot-security.discover-microsoft-copilot-security
title: Discover Microsoft Copilot for Security
metadata:
  title: Discover Microsoft Copilot for Security
  description: "Discover Microsoft Copilot for Security"
  ms.date: 06/19/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/2-discover-microsoft-copilot-security.md)]