### YamlMime:ModuleUnit
uid: learn.wwl.unlock-insights-microsoft-copilot-security.utilize-prompts-microsoft-copilot-security
title: Utilize Prompts in Microsoft Copilot for Security
metadata:
  title: Utilize Prompts in Microsoft Copilot for Security
  description: "Utilize Prompts in Microsoft Copilot for Security"
  ms.date: 06/19/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/6-utilize-prompts-microsoft-copilot-security.md)]