### YamlMime:ModuleUnit
uid: learn.wwl.unlock-insights-microsoft-copilot-security.incorporate-promptbooks-microsoft-copilot-security
title: Incorporate Promptbooks in Microsoft Copilot for Security
metadata:
  title: Incorporate Promptbooks in Microsoft Copilot for Security
  description: "Incorporate Promptbooks in Microsoft Copilot for Security"
  ms.date: 06/19/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/7-incorporate-promptbooks-microsoft-copilot-security.md)]