### YamlMime:ModuleUnit
uid: learn.wwl.unlock-insights-microsoft-copilot-security.explore-new-features-microsoft-copilot-security
title: Explore New Features in Microsoft Copilot for Security
metadata:
  title: Explore New Features in Microsoft Copilot for Security
  description: "Explore New Features in Microsoft Copilot for Security"
  ms.date: 06/19/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 4
content: |
  [!include[](includes/8-explore-new-features-microsoft-copilot-security.md)]