### YamlMime:ModuleUnit
uid: learn.azure.support-hybrid-clouds.4-choose-deployment-model
title: Choose a deployment model
metadata:
  title: Choose a deployment model
  description: Discussion of a potential Azure cloud architecture for several data classifications with Azure Stack Hub and Azure Stack Edge.
  ms.date: 02/08/2023
  author: EliotSeattle
  ms.author: eliotgra
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/4-choose-deployment-model.md)] 