### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-secure-organization-data.introduction-data-security
title: Introduction to data security
metadata:
  title: Introduction to data security
  description: "SC-100 preparatory unit on the topic: introduction to data security."
  ms.date: 3/14/2023
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/1-introduction-data-security.md)]