### YamlMime:ModuleUnit
uid: learn.sports-machine-learning.build-mixed-reality-with-babylonjs.environment-setup
metadata:
  title: Set up your development environment
  description: Set up your development environment with starter code.
  ms.date: 06/15/2021
  author: cassiebreviu
  ms.author: cassieb
  ms.topic: unit
  ms.custom: team=nextgen
title: Set up your development environment
durationInMinutes: 2
content: |
  [!include[](includes/2-environment-setup.md)]
