### YamlMime:ModuleUnit
uid: learn.sports-machine-learning.build-mixed-reality-with-babylonjs.initialize-environment
metadata:
  title: Initialize your custom environment in your XR experience
  description: Initialize your custom environment in your XR experience.
  ms.date: 06/15/2021
  author: cassiebreviu
  ms.author: cassieb
  ms.topic: unit
  ms.custom: team=nextgen
title: Initialize your custom environment in your XR experience
durationInMinutes: 5
content: |
  [!include[](includes/8-initialize-environment.md)]
