### YamlMime:ModuleUnit
uid: learn.secure-your-azure-virtual-machine-disks.5-automate-secure-vm-deployments-using-arm-templates
title: Automate secure VM deployments by adding encryption to Azure Resource Manager templates
metadata:
  title: Automate secure VM deployments by adding encryption to Azure Resource Manager templates
  description: Automate secure VM deployments by adding encryption to Azure Resource Manager templates
  ms.date: 12/29/2023
  author: roygara
  ms.author: rogarana
  ms.topic: unit
  ms.custom:
    - devx-track-arm-template
durationInMinutes: 5
content: |
  [!include[](includes/5-automate-secure-vm-deployments-using-arm-templates.md)]
