### YamlMime:ModuleUnit
uid: learn.wwl.use-sap-workload-planning-deployment-checklist.examine
title: Examine the SAP workload planning and deployment checklist
metadata:
  title: Examine the SAP workload planning and deployment checklist
  description: "Examine the SAP workload planning and deployment checklist"
  ms.date: 04/20/2023
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/2-examine-sap-workload-planning-deployment-checklist.md)]