### YamlMime:ModuleUnit
uid: learn.wwl.deployment-readiness.assess-application-compatibility
title: Assess application compatibility
metadata:
  title: Assess application compatibility
  description: "Assess application compatibility"
  ms.date: 04/22/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/4-assess-application-compatibility.md)]