### YamlMime:ModuleUnit
uid: learn.wwl.deployment-readiness.explore-tools-for-application-compatibility-mitigation
title: Explore tools for application compatibility mitigation
metadata:
  title: Explore tools for application compatibility mitigation
  description: "Explore tools for application compatibility mitigation"
  ms.date: 04/22/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 4
content: |
  [!include[](includes/5-explore-tools-for-application-compatibility-mitigation.md)]