### YamlMime:ModuleUnit
uid: learn.mixed-reality-toolkit-project-unity.3-exercise-configure
title: Exercise - Configure Unity for Windows Mixed Reality
metadata:
  title: Exercise - Configure Unity for Windows Mixed Reality
  description: Configure Unity for Windows Mixed Reality development.
  ms.date: 01/12/2024
  author: marlenaklein-msft
  ms.author: marlenaklein
  ms.topic: unit
  ms.custom:
  - team=cloud_advocates
  ms.contributors:
  - apspeigh-08242020
durationInMinutes: 10
content: |
  [!include[](includes/3-exercise-configure.md)]
