### YamlMime:ModuleUnit
uid: learn.wwl.manage-identity-projects-pipelines-agents.configure-agent-identities
title: Configure agent identities
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure agent identities
  description: "Configure agent identities."
  ms.date: 1/25/2023
  author: LuizMacedo
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/4-configure-agent-identities.md)]
