### YamlMime:ModuleUnit
uid: learn.wwl.implement-desired-state-configuration-dsc.explore-desired-state-configuration-dsc
title: Explore Desired State Configuration (DSC)
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Explore Desired State Configuration (DSC)
  description: "Explore Desired State Configuration (DSC)"
  ms.date: 05/23/2024
  author: wwlpublish
  ms.author: lumac
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 3
content: |
  [!include[](includes/3-explore-desired-state-configuration-dsc.md)]
