### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-storage-for-azure-virtual-desktop.configure-fslogix-components
title: Configure storage for FSLogix components
metadata:
  title: Configure storage for FSLogix components
  description: "Configure storage for FSLogix components"
  ms.date: 08/12/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/3-configure-storage-fslogix-components.md)]