### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-storage-for-azure-virtual-desktop.configure-storage-accounts
title: Configure storage accounts
metadata:
  title: Configure storage accounts
  description: "Configure storage accounts"
  ms.date: 08/12/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/4-configure-storage-accounts.md)]