### YamlMime:ModuleUnit
uid: learn.wwl.implement-manage-storage-for-azure-virtual-desktop.configure-disks
title: Configure disks
metadata:
  title: Configure disks
  description: "Configure disks"
  ms.date: 08/12/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/6-configure-disks.md)]