### YamlMime:ModuleUnit
uid: learn.wwl.deploy-iaas-solutions-with-azure-sql.explore-performance-and-security
title: Explore performance and security
metadata:
  title: Explore performance and security
  description: "Explore performance and security"
  ms.date: 12/22/2022
  author: wwlpublish
  ms.author: jupadrao
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 13
content: |
  [!include[](includes/4-explore-performance-and-security.md)]