### YamlMime:ModuleUnit
uid: learn.wwl.design-implement-network-security-monitoring.implement-web-application-firewall-on-azure-front-door
title: Implement a Web Application Firewall on Azure Front Door
metadata:
  title: Implement a Web Application Firewall on Azure Front Door
  description: "Implement a Web Application Firewall on Azure Front Door"
  ms.date: 11/29/2024
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/10-implement-web-application-firewall-on-azure-front-door.md)]
quiz:
  title: "Check your knowledge"
  questions:
  - content: "What are the two modes that a WAF policy can use?"
    choices:
    - content: "WAF policy can either be in Default mode or Custom mode."
      isCorrect: false
      explanation: "Incorrect. There are no modes called Default or Custom."
    - content: "WAF policy can either be in Default Rule Set mode or Detection mode."
      isCorrect: false
      explanation: "Incorrect. By default, the WAF policy is in Detection mode, however there's no mode called Default Rule Set."
    - content: "WAF policy can either be in Prevention mode or Detection mode."
      isCorrect: true
      explanation: "Correct. By default, the WAF policy is in Detection mode, but you can change it to Prevention mode."
  - content: "What are the two types of custom rule in a WAF policy?"
    choices:
    - content: "String rules and match rules."
      isCorrect: false
      explanation: "Incorrect. There are two types of custom rules: match rules and rate limit rules. There's no string rule."
    - content: "Match rules and rate limit rules."
      isCorrect: true
      explanation: "Correct. There are two types of custom rules: match rules and rate limit rules."
    - content: "Priority rules and rate limit rules."
      isCorrect: false
      explanation: "Incorrect. There are two types of custom rules: match rules and rate limit rules. There's no priority rule."