### YamlMime:ModuleUnit
uid: learn.wwl.design-implement-network-security-monitoring.exercise-configure-ddos-protection-virtual-network-using-azure-portal
title: 'Exercise: Configure DDoS Protection on a virtual network using the Azure portal'
metadata:
  title: 'Exercise: Configure DDoS Protection on a virtual network using the Azure portal'
  description: "Exercise: Configure DDoS Protection on a virtual network using the Azure portal"
  ms.date: 11/29/2024
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 12
content: |
  [!include[](includes/4-exercise-configure-ddos-protection-virtual-network-using-azure-portal.md)]