### YamlMime:ModuleUnit
uid: learn.wwl.design-implement-network-security-monitoring.exercise-deploy-configure-azure-firewall-using-azure-portal
title: 'Exercise: Deploy and configure Azure Firewall using the Azure portal'
metadata:
  title: 'Exercise: Deploy and configure Azure Firewall using the Azure portal'
  description: "Exercise: Deploy and configure Azure Firewall using the Azure portal"
  ms.date: 11/29/2024
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 18
content: |
  [!include[](includes/7-exercise-deploy-configure-azure-firewall-using-azure-portal.md)]