### YamlMime:ModuleUnit
uid: learn.ai-security-controls.implement-ai-data-security
title: Implement AI data security
metadata:
  title: Implement AI data security
  description: Learn about AI data security and how to implement it in your AI systems
  ms.date: 07/24/2024
  author: sarah-yo
  ms.author: sayoung
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/4-implement-ai-data-security.md)]
