### YamlMime:ModuleUnit
uid: learn.ai-security-controls.implementing-ai-data-security
title: Implementing AI data security
metadata:
  title: Implementing AI data security
  description: TBD
  ms.date: 07/24/2024
  author: sarah-yo
  ms.author: sayoung
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/4-implementing-ai-data-security.md)]
