### YamlMime:ModuleUnit
uid: learn.ai-security-controls.implementing-application-security-best-practices-for-ai-enabled-applications
title: Implementing application security best practices for AI enabled applications
metadata:
  title: Implementing application security best practices for AI enabled applications
  description: TBD
  ms.date: 07/24/2024
  author: sarah-yo
  ms.author: sayoung
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/7-implementing-application-security-best-practices-for-ai-enabled-applications.md)]
