### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-secure-applications.introduction-application-security
title: Introduction to application security
metadata:
  title: Introduction to application security
  description: "SC-100 preparatory unit on this topic: introduction to application security."
  ms.date: 3/14/2023
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 7
content: |
  [!include[](includes/1-introduction-application-security.md)]