### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-secure-applications.design-implement-standards-secure-application-development
title: Design and implement standards to secure application development
metadata:
  title: Design and implement standards to secure application development
  description: "SC-100 preparatory unit on this topic: design and implement standards to secure application development."
  ms.date: 3/14/2023
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 20
content: |
  [!include[](includes/2-design-implement-standards-secure-application-development.md)]