### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-secure-applications.design-solution-api-management-security
title: Design a solution for API management and security
metadata:
  title: Design a solution for API management and security
  description: "SC-100 preparatory unit on this topic: design a solution for API management and security."
  ms.date: 3/15/2023
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 12
content: |
  [!include[](includes/7-design-solution-api-management-security.md)]
