### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-secure-applications.design-solution-secure-access-applications
title: Design a solution for secure access to applications
metadata:
  title: Design a solution for secure access to applications
  description: "SC-100 preparatory unit on this topic: design a solution for secure access to applications."
  ms.date: 3/15/2023
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 15
content: |
  [!include[](includes/8-design-solution-secure-access-applications.md)]
