### YamlMime:ModuleUnit
uid: learn.wwl.get-started-github-copilot.exercise-configure-github-copilot-extensions-visual-studio-code
title: Exercise - Configure GitHub Copilot extensions for Visual Studio Code
metadata:
  title: Exercise - Configure GitHub Copilot extensions for Visual Studio Code
  description: Exercise - Configure GitHub Copilot extensions for Visual Studio Code
  author: wwlpublish
  ms.author: cahowd
  ms.date: 07/24/2024
  ms.topic: unit
  ms.collection:
    - wwl-ai-copilot
durationInMinutes: 10
content: |
  [!include[](includes/7-exercise-configure-github-copilot-extensions-visual-studio-code.md)]
