### YamlMime:ModuleUnit
uid: learn.wwl.microsoft-defender-cloud-threat-protection.devops-environment-security-posture
title: DevOps environment security posture
metadata:
  title: DevOps environment security posture
  description: "DevOps environment security posture"
  ms.date: 05/10/2024
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - references_regions
durationInMinutes: 3
content: |
  [!include[](includes/17-devops-environment-security-posture.md)]