### YamlMime:ModuleUnit
uid: learn.wwl.microsoft-defender-cloud-threat-protection.configure-microsoft-defender-containers-components
title: Configure Microsoft Defender for Containers components
metadata:
  title: Configure Microsoft Defender for Containers components
  description: "Configure Microsoft Defender for Containers components"
  ms.date: 05/10/2024
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - references_regions
durationInMinutes: 3
content: |
  [!include[](includes/8-configure-microsoft-defender-containers-components.md)]