### YamlMime:ModuleUnit
uid: learn.wwl.explore-enterprise-desktop.plan-application-deployment
title: Plan an application deployment
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Plan an application deployment
  description: "Plan an application deployment"
  ms.date: 09/09/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/6-plan-application-deployment.md)]
