### YamlMime:ModuleUnit
uid: learn.wwl.explore-azure-governance-manageability.automation
title: Explore Azure Automation
metadata:
  title: Explore Azure Automation
  description: "Explore Azure Automation"
  ms.date: 11/08/2023
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom: linux-related-content
durationInMinutes: 4
content: |
  [!include[](includes/9-explore-azure-automation.md)]
