### YamlMime:ModuleUnit
uid: learn.wwl.understand-scalability-power-bi.configure-large-datasets
title: Configure large datasets
metadata:
  title: Configure large datasets
  description: "Configure large datasets"
  ms.date: 05/15/2024
  author: wwlpublish
  ms.author: anrudduc
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/4-configure-large-datasets.md)]