### YamlMime:ModuleUnit
uid: learn.wwl.run-containers-windows-server.prepare-2019-host-for-container-deployment
title: Prepare a Windows Server 2019 host for container deployment
metadata:
  title: Prepare a Windows Server 2019 host for container deployment
  description: "Prepare a Windows Server 2019 host for container deployment"
  ms.date: 04/15/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/6-prepare-windows-server-host-for-container-deployment.md)]