### YamlMime:ModuleUnit
uid: learn.wwl.explore-azure-pipelines.explore-concept-of-pipelines-devops
title: Explore the concept of pipelines in DevOps
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Explore the concept of pipelines in DevOps
  description: "Explore the concept of pipelines in DevOps"
  ms.date: 05/07/2024
  author: wwlpublish
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/2-explore-concept-of-pipelines-devops.md)]
