### YamlMime:ModuleUnit
uid: learn.wwl.explore-azure-pipelines.summary
title: Summary
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Summary
  description: "Summary"
  ms.date: 05/07/2024
  author: wwlpublish
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 1
content: |
  [!include[](includes/6-summary.md)]
