### YamlMime:ModuleUnit
uid: learn.azure.aspnet-configurationbuilder.3-aspnet-configurationbuilder-overview
title: Use the ConfigurationBuilder type
metadata:
  title: Use the ConfigurationBuilder type
  description: This unit explains the purpose of the ConfigurationBuilder type, and how to use it in an ASP.NET web app.
  ms.date: 01/16/2024
  author: coderandhiker
  ms.author: chrisrt
  ms.manager: markl
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/3-aspnet-configurationbuilder-overview.md)]
  
