### YamlMime:ModuleUnit
uid: learn.azure.aspnet-configurationbuilder.4-exercise-aspnet-configurationbuilder
title: Exercise - Configure an Azure web app with ConfigurationBuilder
metadata:
  title: Exercise - Configure an Azure web app with ConfigurationBuilder
  description: In this unit, you use ConfigurationBuilder to configure an Azure web app and help protect sensitive configuration data.
  ms.date: 01/16/2024
  author: coderandhiker
  ms.author: chrisrt
  ms.manager: markl
  ms.topic: unit
  ms.custom:
    - devx-track-azurepowershell
durationInMinutes: 10
interactive: powershell
azureSandbox: true
content: |
  [!include[](includes/4-exercise-aspnet-configurationbuilder.md)]
# NOTE: Task validation is failing for learners, so that is disabled for now.
# tasks:
# - action: exists
#   environment: azure
#   hint: "Create an Azure key vault."
#   azure:
#     resource:
#       type: "Microsoft.KeyVault/vaults"
