### YamlMime:ModuleUnit
uid: learn.wwl.manage-security-controls-identity-access.configure-role-management-access-reviews-microsoft-entra-id-governance
title: Configure role management and access reviews by using Microsoft Entra ID Governance
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure role management and access reviews by using Microsoft Entra ID Governance
  description: "Configure role management and access reviews by using Microsoft Entra ID Governance"
  ms.date: 02/06/2025
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/49-configure-role-management-access-reviews-microsoft-entra-id-governance.md)]