### YamlMime:ModuleUnit
uid: learn.azure.migrate-linux-postgres.configure-linux-application-workload
title: Configure a Linux application workload​
metadata:
  title: Configure a Linux application workload​
  description: "Configure a Linux application workload in Azure. Learn how to deploy a sample application on your Linux virtual machine. Explore how to connect to your Azure Database for PostgreSQL server."
  ms.date: 9/16/2024
  author: asw101
  ms.author: aawislan
  ms.topic: unit
###########################################################################
###
### If your content is related to a product or service, apply one value from
### the ms.service allowlist.
###
### If your content isn't about a product or service, you can omit the ms.service field.
###
### For the list of approved ms.service values, go to
### https://review.learn.microsoft.com/help/platform/metadata-taxonomies?branch=main#msservice.
###
### To request new values, go to
### https://review.learn.microsoft.com/help/platform/metadata-reporting-taxonomy-requests?branch=main.
durationInMinutes: 45
content: |
  [!include[](includes/3-configure-linux-application-workload.md)]