### YamlMime:ModuleUnit
uid: learn.wwl.just-enough-administration-windows-server.create-session-configuration-file-to-register-jea-endpoint
title: Create a session configuration file to register a JEA endpoint
metadata:
  title: Create a session configuration file to register a JEA endpoint
  description: "Create a session configuration file to register a JEA endpoint"
  ms.date: 05/05/2023
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/4-create-session-configuration-file-to-register-jea-endpoint.md)]