### YamlMime:ModuleUnit
uid: learn.wwl.automate-machine-learning-workflows.azure-pipelines
title: Azure Pipelines
metadata:
  title: Azure Pipelines
  description: "Azure Pipelines"
  ms.date: 07/10/2024
  author: wwlpublish
  ms.author: madiepev
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 9
content: |
  [!include[](includes/3-azure-pipelines.md)]