### YamlMime:ModuleUnit
uid: learn.wwl.pass-pipeline-objects.expand-property-values
title: Expand property values
metadata:
  title: Expand property values
  description: "Expand property values"
  ms.date: 03/22/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
azureSandbox: false
labModal: false
durationInMinutes: 8
content: |
  [!include[](includes/9-expand-property-values.md)]