### YamlMime:ModuleUnit
uid: learn.wwl.configure-virtual-machine-extensions.implement-desired-state-configuration
title: Implement Desired State Configuration
metadata:
  title: Implement Desired State Configuration
  description: "Implement a Desired State Configuration extension with your virtual machines."
  ms.date: 12/19/2022
  author: wwlpublish
  ms.author: cynthist
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/4-implement-desired-state-configuration.md)]