### YamlMime:ModuleUnit
uid: learn.wwl.learn-continuous-integration-github-actions.examine-environment-variables
title: Examine environment variables
metadata:
  title: Examine environment variables
  description: "Examine environment variables"
  ms.date: 05/08/2024
  author: wwlpublish
  ms.author: lumac
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/3-examine-environment-variables.md)]