### YamlMime:ModuleUnit
uid: learn.challenge-project-building-augmented-reality-app-hololens-two.application-description-and-storyboarding
title: Application description and storyboarding
metadata:
  title: Application description and storyboarding
  description: "This unit describes how to create an app description and storyboard for a HoloLens app prototype."
  ms.date: 7/25/2023
  author: tholewis
  ms.author: tholewis
  ms.topic: unit
durationInMinutes: 60
content: |
  [!include[](includes/2-application-description-and-storyboarding.md)]