### YamlMime:ModuleUnit
uid: learn.challenge-project-building-augmented-reality-app-hololens-two.design-and-environmental-considerations
title: Design and environmental considerations
metadata:
  title: Design and environmental considerations
  description: "This unit describes how to create design and environmental considerations for a HoloLens app prototype."
  ms.date: 7/25/2023
  author: tholewis
  ms.author: tholewis
  ms.topic: unit
durationInMinutes: 60
content: |
  [!include[](includes/3-design-and-environmental-considerations.md)]