### YamlMime:ModuleUnit
uid: learn.wwl.use-methods-to-accept-user-inputs-windows-powershell-scripts.identify-values-that-might-change
title: Identify values that might change in Windows PowerShell scripts
metadata:
  title: Identify values that might change in Windows PowerShell scripts
  description: "Identify values that might change in Windows PowerShell scripts"
  ms.date: 03/26/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 3
content: |
  [!include[](includes/2-identify-values-that-might-change.md)]