### YamlMime:ModuleUnit
uid: learn.wwl.implement-tools-to-track-usage-flow.explore-application-insights
title: Explore Application Insights
metadata:
  title: Explore Application Insights
  description: "Explore Application Insights"
  ms.date: 05/24/2024
  author: wwlpublish
  ms.author: lumac
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 5
content: |
  [!include[](includes/6-explore-application-insights.md)]