### YamlMime:ModuleUnit
uid: learn.wwl.implement-tools-to-track-usage-flow.implement-application-insights
title: Implement Application Insights
metadata:
  title: Implement Application Insights
  description: "Implement Application Insights"
  ms.date: 05/24/2024
  author: wwlpublish
  ms.author: lumac
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 3
content: |
  [!include[](includes/7-implement-application-insights.md)]