### YamlMime:ModuleUnit
uid: learn.wwl.deploy-applications.deploy-applications-intune
title: Deploy applications with Intune
metadata:
  title: Deploy applications with Intune
  description: "Deploy applications with Intune"
  ms.date: 06/07/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 3
content: |
  [!include[](includes/2-deploy-applications-intune.md)]