### YamlMime:ModuleUnit
uid: learn.wwl.deploy-applications.deploy-applications-configuration-manager
title: Deploy applications with Configuration Manager
metadata:
  title: Deploy applications with Configuration Manager
  description: "Deploy applications with Configuration Manager"
  ms.date: 06/07/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 8
content: |
  [!include[](includes/5-deploy-applications-configuration-manager.md)]