### YamlMime:ModuleUnit
uid: learn.wwl.implement-ip-address-management.configure-ipam-options
title: Configure IP Address Management options
metadata:
  title: Configure IP Address Management options
  description: "Configure IP Address Management options"
  ms.date: 04/15/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/5-configure-ip-address-management-options.md)]