### YamlMime:ModuleUnit
uid: learn.wwl.work-environments-github-actions.set-up-environments
title: Set up environments
metadata:
  title: Set up environments
  description: "Set up environments"
  ms.date: 09/26/2022
  author: wwlpublish
  ms.author: madiepev
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/4-set-up-environments.md)]