### YamlMime:ModuleUnit
uid: learn.wwl.implement-compliance-controls-for-sensitive-data.implement-row-level-security
title: Implement Row Level security
metadata:
  title: Implement Row Level security
  description: "Implement Row Level security"
  ms.date: 09/02/2022
  author: wwlpublish
  ms.author: jupadrao
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 8
content: |
  [!include[](includes/5-implement-row-level-security.md)]