### YamlMime:ModuleUnit
uid: learn-wwl.explore-security-practices-sql-database.configure-managed-identity
title: Configure Managed Identity
metadata:
  title: Configure Managed Identity
  description: "Learn how to configure Managed Identity for Azure SQL Database."
  ms.date: 09/27/2024
  author: jupadrao
  ms.author: jupadrao
  ms.topic: unit
durationInMinutes: 7
content: |
  [!include[](includes/3-configure-managed-identity.md)]