uid: learn.azure.build-intelligent-spring-apps-using-ai.2-environment-setup
title: Setting Up Your Development Environment
metadata:
  title: Setting Up Your Development Environment
  description: >-
    Configure your local environment and Azure resources for
    Spring AI development
  ms.date: 02/24/2025
  author: gok
  ms.author: gok
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/2-environment-setup.md)]
