### YamlMime:ModuleUnit
uid: learn.wwl.automate-deployment-of-sap-azure.exercise-terraform-deployment-for-infrastructure
title: Exercise - Define a Terraform deployment for an Azure VM
metadata:
  title: Exercise - Define a Terraform deployment for an Azure VM
  description: "Exercise - Define a Terraform deployment for an Azure VM"
  ms.date: 08/16/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 9
content: |
  [!include[](includes/4-exercise-define-terraform-deployment-for-azure-virtual-machine.md)]