### YamlMime:ModuleUnit
uid: learn.wwl.configure-bitlocker-disk-encryption-for-windows-iaas-vms.configure-key-vault-for-azure
title: Configure Key Vault for Azure Disk Encryption
metadata:
  title: Configure Key Vault for Azure Disk Encryption
  description: "Configure Key Vault for Azure Disk Encryption"
  ms.date: 07/27/2022
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
    - devx-track-azurecli
azureSandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/3-configure-key-vault-azure.md)]
