### YamlMime:ModuleUnit
uid: learn.github.github-actions-automate-tasks.2c-configure-github-actions-workflow
title: Configure a GitHub Actions workflow
metadata:
  title: Configure a GitHub Actions workflow
  description: Learn common configurations within a workflow file. See workflow examples and best practice recommendations for action stability and security.
  ms.date: 10/06/2023
  author: juliakm
  ms.author: jukullam
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/2c-configure-github-actions-workflow.md)]
