### YamlMime:ModuleUnit
uid: learn.azure.intro-to-java-azure.6-sample-deployment
metadata:
  title: Sample Java app deployment
  description: We demonstrate and explain a Java app deployment to Azure App Service
  ms.date: 05/01/2023
  author: SandraAhlgrimm
  ms.author: sakriema
  ms.topic: unit
  ms.custom:
    - team=cloud_advocates
    - devx-track-extended-java
  ms.contributors:
  - sakriema-12042020
title: Sample Java app deployment
durationInMinutes: 3
content: |
  [!include[](includes/6-sample-deployment.md)]
