### YamlMime:ModuleUnit
uid: learn.wwl.deploy-single-instance-implementations-2-tier-3-tier.explore-deployment-methodologies
title: Explore deployment methodologies
metadata:
  title: Explore deployment methodologies
  description: "Explore different methodologies for deploying single-instance SAP on Azure."
  ms.date: 08/01/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 4
content: |
  [!include[](includes/2-explore-deployment-methodologies.md)]