### YamlMime:ModuleUnit
uid: learn.manage-devices-with-microsoft-endpoint-manager.4-configure-devices
title: Understand device configuration
metadata:
  title: Understand device configuration
  description: Learn about configuring devices using Microsoft Intune.
  ms.date: 05/08/2023
  author: Erikre
  ms.author: erikre
  ms.topic: unit
durationInMinutes: 2
content: |
  [!include[](includes/4-configure-devices.md)]
