### YamlMime:ModuleUnit
uid: learn.wwl.create-configure-data-loss-prevention-policies.configure-data-loss-prevention-policies-for-power-platform
title: Configure data loss prevention policies for Power Platform
metadata:
  title: Configure data loss prevention policies for Power Platform
  description: "Configure data loss prevention policies for Power Platform"
  ms.date: 08/18/2022
  author: wwlpublish
  ms.author: bneeb
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/2-configure-data-loss-prevention-policies-for-power-platform.md)]