### YamlMime:ModuleUnit
uid: learn.wwl.create-configure-data-loss-prevention-policies.configure-file-policies-microsoft-cloud-app-security
title: Configure policies in Microsoft Defender for Cloud Apps
metadata:
  title: Configure policies in Microsoft Defender for Cloud Apps
  description: "Configure policies in Microsoft Defender for Cloud Apps"
  ms.date: 02/16/2023
  author: wwlpublish
  ms.author: riswinto
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/4-configure-file-policies-microsoft-cloud-app-security.md)]