### YamlMime:ModuleUnit
uid: learn.wwl.create-configure-data-loss-prevention-policies.manage-data-loss-prevention-violations
title: Manage data loss prevention violations in Microsoft Defender for Cloud Apps
metadata:
  title: Manage data loss prevention violations in Microsoft Defender for Cloud Apps
  description: "Manage data loss prevention violations in Microsoft Defender for Cloud Apps"
  ms.date: 08/20/2024
  author: wwlpublish
  ms.author: riswinto
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/5-manage-data-loss-prevention-violations-microsoft-cloud-app-security.md)]