### YamlMime:ModuleUnit
uid: learn.language.rust-create-command-line-program.application-outline
metadata:
  title: Outline the application
  description: Identify what the command-line application will do and how to implement it.
  ms.date: 01/21/2022
  author: meaghanlewis
  ms.author: chnoring
  ms.topic: unit
  ms.custom: team=nextgen
title: Outline the application
durationInMinutes: 1
content: |
  [!include[](includes/2-application-outline.md)]
