### YamlMime:ModuleUnit
uid: learn.wwl.manage-windows-365.configure-windows-365
title: Configure Windows 365
metadata:
  title: Configure Windows 365
  description: "Configure Windows 365"
  ms.date: 08/20/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 3
content: |
  [!include[](includes/3-configure-windows-365.md)]