### YamlMime:ModuleUnit
uid: learn.wwl.audit-security-of-windows-server-iaas-vms.enable-azure-security-center-hybrid-environments
title: Enable Azure Security Center in hybrid environments
metadata:
  title: Enable Azure Security Center in hybrid environments
  description: "Enable Azure Security Center in hybrid environments"
  ms.date: 09/24/2020
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
azureSandbox: false
durationInMinutes: 7
content: |
  [!include[](includes/3-enable-azure-security-center-hybrid-environments.md)]