### YamlMime:ModuleUnit
uid: learn.wwl.manage-multi-tenancy-for-azure-stack-hub.configure-multi-tenancy
title: Configure multi-tenancy in Azure Stack Hub
metadata:
  title: Configure multi-tenancy in Azure Stack Hub
  description: "Configure multi-tenancy in Azure Stack Hub"
  ms.date: 10/26/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
  ms.custom:
    - devx-track-arm-template
azureSandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/2-configure-multi-tenancy-azure-stack-hub.md)]
