### YamlMime:ModuleUnit
uid: learn.wwl.manage-multi-tenancy-for-azure-stack-hub.configure-guest-directory
title: Configure Azure Stack Hub guest directory
metadata:
  title: Configure Azure Stack Hub guest directory
  description: "Configure Azure Stack Hub guest directory"
  ms.date: 10/26/2022
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/3-configure-azure-stack-hub-guest-directory.md)]