### YamlMime:ModuleUnit
uid: learn.wwl.implement-azure-load-testing.configure-file
title: Create a load test YAML configuration file
metadata:
  title: Create a load test YAML configuration file
  description: "Load test website home page"
  ms.date: 05/13/2024
  author: wwlpublish
  ms.author: jileary
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 4
content: |
  [!include[](includes/4-configure-file.md)]