### YamlMime:ModuleUnit
uid: learn.azure.azure-cyclecloud-high-performance-computing.exercise-install-configure
title: Exercise - Install and configure Azure CycleCloud
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  unitType: exercise
  title: Exercise - Install and configure Azure CycleCloud
  description: Learn about the process of installing and configuring Azure CycleCloud.
  ms.date: 12/18/2024
  author: ahoward
  ms.author: ahoward
  ms.topic: unit
durationInMinutes: 25
content: |
  [!include[](includes/4-exercise-install-configure.md)]

