### YamlMime:ModuleUnit
uid: learn.student-evangelism.predict-basketball-player-efficiency-ratings.2-set-up-local-environment
metadata:
  title: Exercise - Set up your local environment for data science coding
  description: Ensure your local environment is set up for data science coding, and download data for basketball analysis.
  ms.date: 03/10/2021
  author: softchris
  ms.author: chnoring
  ms.topic: unit
  ms.custom:
    - team=nextgen
    - devx-track-python
title: Exercise - Set up your local environment for data science coding
durationInMinutes: 3
content: |
  [!include[](includes/2-set-up-local-environment.md)]
