### YamlMime:ModuleUnit
uid: learn.student-evangelism.predict-basketball-player-efficiency-ratings.3-find-missing-values
metadata:
  title: 'Exercise - Data cleansing part 1 - Find missing values'
  description: Explore the data and discover any missing values to reduce the data size for more accurate insights.
  ms.date: 03/10/2021
  author: softchris
  ms.author: chnoring
  ms.topic: unit
  ms.custom: team=nextgen
title: 'Exercise - Data cleansing part 1 - Find missing values'
durationInMinutes: 3
content: |
  [!include[](includes/3-find-missing-values.md)]
