### YamlMime:ModuleUnit
uid: learn.azure.pc-holographic-remoting-tutorials-mrtk.4-create-holographic-remoting-pc-application
title: Create a Holographic Remoting PC application
metadata:
  title: Create a Holographic Remoting PC application
  description: Introduction to create Holographic Remoting pc application
  ms.date: 01/03/2024
  author: marlenaklein-msft
  ms.author: marlenaklein
  ms.topic: unit
durationInMinutes: 1
content: |
  [!include[](includes/4-create-holographic-remoting-pc-application.md)]
