### YamlMime:ModuleUnit
uid: learn.azure.pc-holographic-remoting-tutorials-mrtk.5-exercise-create-holographic-remoting-pc-application
title: Exercise - Create a Holographic Remoting PC application
metadata:
  title: Exercise - Create a Holographic Remoting PC application
  description: Introduction to Create Holographic Remoting PC application
  ms.date: 01/03/2024
  author: marlenaklein-msft
  ms.author: marlenaklein
  ms.topic: unit
durationInMinutes: 4
content: |
  [!include[](includes/5-exercise-create-holographic-remoting-pc-application.md)]
