### YamlMime:ModuleUnit
uid: learn-sqlserver.test-optimize-sql-server-databases-using-dea.4-configure-new-capture
title: Configure a new capture
metadata:
  title: Configure a new capture
  description: "Configure a new capture"
  ms.date: 12/01/2021
  author: wwlpublish
  ms.author: markohot
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/4-configure-new-capture.md)]