### YamlMime:ModuleUnit
uid: learn-sqlserver.test-optimize-sql-server-databases-using-dea.7-exercise-configure-new-capture
title: Exercise - Configure a new capture with DEA
metadata:
  title: Exercise - Configure a new capture with DEA
  description: "Exercise - Configure a new capture with DEA"
  ms.date: 12/01/2021
  author: wwlpublish
  ms.author: markohot
  ms.topic: unit
azureSandbox: true
labModal: false
durationInMinutes: 10
content: |
  [!include[](includes/7-exercise-configure-new-capture.md)]
interactive: bash