### YamlMime:ModuleUnit
uid: learn.wwl.troubleshoot-premises-hybrid-networking.diagnose-ip-configuration-issues
title: Diagnose IP configuration issues
metadata:
  title: Diagnose IP configuration issues
  description: "Diagnose IP configuration issues"
  ms.date: 03/26/2024
  author: wwlpublish
  ms.author: tonyj
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 9
content: |
  [!include[](includes/4-diagnose-ip-configuration-issues.md)]