### YamlMime:ModuleUnit
uid: learn.implement-azure-database-for-mysql-flexible-server-features-that-support-mission-critical-workloads.configure-business-continuity-and-disaster-recovery
title: Configure business continuity and disaster recovery
metadata:
  title: Configure business continuity and disaster recovery
  description: "This unit reviews implementing business continuity and disaster recovery features for Azure Database for MySQL - Flexible Server. It covers high availability, and backup and restore."
  ms.date: 3/29/2024
  author: shreyaaithal
  ms.author: shaithal
  ms.reviewer: maghan
  ms.topic: unit
durationInMinutes: 1
content: |
  [!include[](includes/3-configure-business-continuity-and-disaster-recovery.md)]
