### YamlMime:ModuleUnit
uid: learn.wwl.specify-requirements-secure-saas-paas-iaas-services.evaluate-ai-services-security
title: Evaluate AI Services security
metadata:
  title: Evaluate AI Services security
  description: "SC-100 preparatory unit on the topic: Evaluate AI Services security."
  ms.date: 5/21/2024
  author: hrasheed-msft
  ms.author: hrasheed
  ms.topic: unit
durationInMinutes: 10
content: |
  [!include[](includes/6-evaluate-ai-services-security.md)]
