### YamlMime:ModuleUnit
uid: learn.cmu-cloud-admin.cmu-orchestration.1-automation
title: What is automation?
metadata:
  title: What is automation?
  description: What is automation?
  ms.date: 06/07/2022
  author: softchris
  ms.author: chnoring
  ms.topic: unit
  ms.custom: team=nextgen
durationInMinutes: 3
content: |
  [!include[](includes/1-automation.md)]
