### YamlMime:ModuleUnit
uid: learn.azure.improve-developer-experience-of-an-api-with-swagger-documentation.exercise-use-swagger-ui
title: Exercise - Customize and extend your OpenAPI documentation with XML comments and annotations
metadata:
  title: Exercise - Customize and extend your OpenAPI documentation with XML comments and annotations
  description: Exercise - Customize and extend your OpenAPI documentation with XML comments and annotations
  ms.date: 11/16/2023
  author: camsoper
  ms.author: casoper
  ms.topic: unit
  zone_pivot_groups: 
durationInMinutes: 12
content: |
  [!include[](includes/5-exercise-use-swagger-ui.md)]