### YamlMime:ModuleUnit
uid: learn.azure.build-enterprise-ai-agents-with-java-spring.9-exercise-aca-deployment
title: Exercise - Deploy a Spring AI application to Azure Container Apps
metadata:
  title: Exercise - Deploy Spring AI Application to Azure Container Apps
  description: Learn how to deploy your Spring AI application to Azure Container Apps.
  ms.date: 03/02/2025
  author: KarlErickson
  ms.author: karler
  ms.reviewer: jbalderas, gok
  ms.topic: unit
  ms.collection: ce-skilling-ai-copilot
durationInMinutes: 15
content: |
  [!include[](includes/9-exercise-aca-deployment.md)]
