### YamlMime:ModuleUnit
uid: learn.wwl.optimize-microsoft-intune-microsoft-copilot-security-integration.leverage-prompting-features-microsoft-copilot-security
title: Leverage prompting features in Microsoft Copilot for Security
metadata:
  title: Leverage prompting features in Microsoft Copilot for Security
  description: "Leverage prompting features in Microsoft Copilot for Security"
  ms.date: 06/21/2024
  author: wwlpublish
  ms.author: rstearman
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/8-leverage-prompting-features-microsoft-copilot-security.md)]