### YamlMime:ModuleUnit
uid: learn.azure.publish-azure-web-app-with-azure-toolkit-eclipse.manage-deployment-eclipse
title: Manage app deployments from Eclipse
metadata:
  title: Manage app deployments from Eclipse
  description: Learn how the Azure Toolkit offers several tools in the Azure Explorer that you can use to manage, configure, and redeploy web apps to an Azure App Service. 
  ms.date: 06/06/2024
  author: cephalin
  ms.author: cephalin
  ms.topic: unit
durationInMinutes: 5
content: |
  [!include[](includes/6-manage-deployment-eclipse.md)]
