### YamlMime:ModuleUnit
uid: learn.wwl.set-up-microsoft-defender-cloud.configure-microsoft-defender-for-cloud-policies
title: Configure Microsoft Defender for Cloud policies
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure Microsoft Defender for Cloud policies
  description: "Configure Microsoft Defender for Cloud policies"
  ms.date: 04/24/2024
  author: wwlpublish
  ms.author: serlingdavis
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 10
content: |
  [!include[](includes/11-configure-microsoft-defender-for-cloud-policies.md)]
