### YamlMime:ModuleUnit
uid: learn.azure.publish-azure-web-app-with-azure-toolkit-intellij.6-manage-deployment-intellij
title: Manage app deployments from IntelliJ IDEA
metadata:
  title: Manage app deployments from IntelliJ IDEA
  description: In this unit, you'll learn how to use the Azure Toolkit for IntelliJ to manage your deployed web apps.
  ms.date: 03/18/2024
  author: bmitchell287
  ms.author: brendm
  ms.topic: unit
durationInMinutes: 7
content: |
  [!include[](includes/6-manage-deployment-intellij.md)]
