### YamlMime:ModuleUnit
uid: learn.azure-security.secure-aad-users-with-mfa.configure-authentication-methods
metadata:
<<<<<<< HEAD
  title: Configure multifactor authentication methods
  description: Configure multifactor authentication methods
  ms.date: 11/01/2024
=======
  adobe-target: true
  prefetch-feature-rollout: true
  title: Configure multi-factor authentication methods
  description: Configure multi-factor authentication methods
  ms.date: 11/03/2023
>>>>>>> 5098a1d1e7a90a838f13a7212f124f89c06e55f8
  author: Justinha
  ms.author: justinha
  ms.topic: unit
title: Configure multifactor authentication methods
durationInMinutes: 6
content: |
  [!include[](includes/5-configure-authentication-methods.md)]
quiz:
   title: Check your knowledge
   questions:
   - content: Which of the following authentication methods is _not_ available for MFA?
     choices:
     - content: Text message
       isCorrect: false
     - content: Microsoft Authenticator app
       isCorrect: false
     - content: Security questions
       isCorrect: true
       explanation: "Correct. Security questions can only be used with Self-Service Password Reset."
   - content: Which of the following authentication methods _can't_ be disabled?
     choices:
     - content: Text message
       isCorrect: false
     - content: Password
       isCorrect: true
       explanation: "Correct. Passwords are always usable as an authentication method and cannot be disabled."
     - content: Microsoft Authenticator app
       isCorrect: false
   - content: True or False. You must activate multifactor authentication for all users in the directory you enable it in.
     choices:
     - content: "True"
       isCorrect: false
     - content: "False"
       isCorrect: true
       explanation: "Correct. MFA can be enabled for a subset of your users, whcih is actually a recommendation. Start small to ensure you don't lock someone out of your systems."
