### YamlMime:ModuleUnit
uid: learn.build-chat-app-web-pubsub.exercise-create-configure-static-web-app
title: Exercise - Create and configure a static web app 
metadata:
  title: Exercise - Create and configure a static web app
  sandbox: true
  interactive: bash
  description: Exercise - Create and configure a static web app, configure the Web PubSub event handler, and view the web site
  ms.date: 02/03/2023
  author: dlepow
  ms.author: danlep
  ms.topic: unit
  ms.custom: devx-track-azurecli
  ms.contributors: jixin
durationInMinutes: 10
content: |
  [!include[](includes/4-exercise-create-configure-static-web-app.md)]
