### YamlMime:ModuleUnit
### YamlMime:ModuleUnit
uid: learn.build-chat-app-web-pubsub.configure-continuous-delivery
title: Use continuous delivery
metadata:
  title: Use continuous delivery
  description: Take advantage of continuous delivery of the static web app
  ms.date: 02/03/2023
  author: dlepow
  ms.author: danlep
  ms.topic: unit
  ms.contributors: jixin
durationInMinutes: 3
content: |
  [!include[](includes/5-configure-continuous-delivery.md)]