### YamlMime:ModuleUnit
uid: learn-wwl.get-started-sql-database-application-development.exercise-enable-auto-failover-groups
title: Enable application resilience with auto-failover groups
metadata:
  title: Enable application resilience with auto-failover groups
  description: "Learn how enable application resilience with auto-failover groups in Azure SQL Database."
  ms.date: 09/05/2024
  author: jupadrao
  ms.author: jupadrao
  ms.topic: unit
durationInMinutes: 8
content: |
  [!include[](includes/7-exercise-enable-auto-failover-groups.md)]