### YamlMime:ModuleUnit
uid: learn.wwl.implement-disaster-recovery-for-sap-workloads-azure.deployments-across-azure-regions-azure-site-recovery
title: Implement disaster recovery for SAP deployments across Azure regions with Azure Site Recovery
metadata:
  adobe-target: true
  prefetch-feature-rollout: true
  title: Implement disaster recovery for SAP deployments across Azure regions with Azure Site Recovery
  description: "Implement disaster recovery for SAP deployments across Azure regions with Azure Site Recovery."
  ms.date: 08/01/2024
  author: wwlpublish
  ms.author: eric
  ms.topic: unit
  ms.custom:
  - N/A
durationInMinutes: 7
content: |
  [!include[](includes/6-implement-disaster-recovery-sap-deployments-azure-site-recovery.md)]
