### YamlMime:ModuleUnit
uid: learn.student-evangelism.altair-azure-sphere-program-emulator.exercise-write-altair-basic-application
title: Exercise - Program the Altair emulator by using Altair BASIC
metadata:
  title: Exercise - Program the Altair emulator by using Altair BASIC
  description: In this exercise, follow the steps to program the Altair emulator by using Altair BASIC.
  ms.date: 11/16/2021
  author: gloveboxes
  ms.author: chnoring
  ms.topic: unit
  ms.custom: nextgen
durationInMinutes: 4 # dummy number at present
content: |
  [!include[](includes/05-exercise-write-altair-basic-application.md)]
