### YamlMime:ModuleUnit
uid: learn.student-evangelism.altair-azure-sphere-program-emulator.exercise-configure-front-panel
title: Exercise - Program the Altair by using the front panel
metadata:
  title: Exercise - Program the Altair by using the front panel
  description: In this exercise, follow the steps to program the Altair by using the front panel.
  ms.date: 11/16/2021
  author: gloveboxes
  ms.author: chnoring
  ms.topic: unit
  ms.custom: nextgen
durationInMinutes: 10 # dummy number at present
content: |
  [!include[](includes/07-exercise-configure-front-panel.md)]